// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AlbumFile.proto

package com.miapsoft.opq.proto;

public final class AlbumFile {
  private AlbumFile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AlbumFileProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string imageId = 1;
    /**
     * <code>optional string imageId = 1;</code>
     */
    boolean hasImageId();
    /**
     * <code>optional string imageId = 1;</code>
     */
    java.lang.String getImageId();
    /**
     * <code>optional string imageId = 1;</code>
     */
    com.google.protobuf.ByteString
        getImageIdBytes();

    // optional string albumId = 2;
    /**
     * <code>optional string albumId = 2;</code>
     */
    boolean hasAlbumId();
    /**
     * <code>optional string albumId = 2;</code>
     */
    java.lang.String getAlbumId();
    /**
     * <code>optional string albumId = 2;</code>
     */
    com.google.protobuf.ByteString
        getAlbumIdBytes();

    // optional bytes serverPath = 3;
    /**
     * <code>optional bytes serverPath = 3;</code>
     */
    boolean hasServerPath();
    /**
     * <code>optional bytes serverPath = 3;</code>
     */
    com.google.protobuf.ByteString getServerPath();

    // optional string imageTime = 4;
    /**
     * <code>optional string imageTime = 4;</code>
     */
    boolean hasImageTime();
    /**
     * <code>optional string imageTime = 4;</code>
     */
    java.lang.String getImageTime();
    /**
     * <code>optional string imageTime = 4;</code>
     */
    com.google.protobuf.ByteString
        getImageTimeBytes();

    // optional bytes imageName = 5;
    /**
     * <code>optional bytes imageName = 5;</code>
     */
    boolean hasImageName();
    /**
     * <code>optional bytes imageName = 5;</code>
     */
    com.google.protobuf.ByteString getImageName();

    // optional uint64 length = 6;
    /**
     * <code>optional uint64 length = 6;</code>
     */
    boolean hasLength();
    /**
     * <code>optional uint64 length = 6;</code>
     */
    long getLength();
  }
  /**
   * Protobuf type {@code com.miapsoft.opq.proto.AlbumFileProto}
   *
   * <pre>
   *文件传输
   * </pre>
   */
  public static final class AlbumFileProto extends
      com.google.protobuf.GeneratedMessage
      implements AlbumFileProtoOrBuilder {
    // Use AlbumFileProto.newBuilder() to construct.
    private AlbumFileProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AlbumFileProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AlbumFileProto defaultInstance;
    public static AlbumFileProto getDefaultInstance() {
      return defaultInstance;
    }

    public AlbumFileProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AlbumFileProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              imageId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              albumId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              serverPath_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              imageTime_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              imageName_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              length_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.miapsoft.opq.proto.AlbumFile.internal_static_com_miapsoft_opq_proto_AlbumFileProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.miapsoft.opq.proto.AlbumFile.internal_static_com_miapsoft_opq_proto_AlbumFileProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.miapsoft.opq.proto.AlbumFile.AlbumFileProto.class, com.miapsoft.opq.proto.AlbumFile.AlbumFileProto.Builder.class);
    }

    public static com.google.protobuf.Parser<AlbumFileProto> PARSER =
        new com.google.protobuf.AbstractParser<AlbumFileProto>() {
      public AlbumFileProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AlbumFileProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AlbumFileProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string imageId = 1;
    public static final int IMAGEID_FIELD_NUMBER = 1;
    private java.lang.Object imageId_;
    /**
     * <code>optional string imageId = 1;</code>
     */
    public boolean hasImageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string imageId = 1;</code>
     */
    public java.lang.String getImageId() {
      java.lang.Object ref = imageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imageId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string imageId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getImageIdBytes() {
      java.lang.Object ref = imageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string albumId = 2;
    public static final int ALBUMID_FIELD_NUMBER = 2;
    private java.lang.Object albumId_;
    /**
     * <code>optional string albumId = 2;</code>
     */
    public boolean hasAlbumId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string albumId = 2;</code>
     */
    public java.lang.String getAlbumId() {
      java.lang.Object ref = albumId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          albumId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string albumId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAlbumIdBytes() {
      java.lang.Object ref = albumId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        albumId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes serverPath = 3;
    public static final int SERVERPATH_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString serverPath_;
    /**
     * <code>optional bytes serverPath = 3;</code>
     */
    public boolean hasServerPath() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes serverPath = 3;</code>
     */
    public com.google.protobuf.ByteString getServerPath() {
      return serverPath_;
    }

    // optional string imageTime = 4;
    public static final int IMAGETIME_FIELD_NUMBER = 4;
    private java.lang.Object imageTime_;
    /**
     * <code>optional string imageTime = 4;</code>
     */
    public boolean hasImageTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string imageTime = 4;</code>
     */
    public java.lang.String getImageTime() {
      java.lang.Object ref = imageTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imageTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string imageTime = 4;</code>
     */
    public com.google.protobuf.ByteString
        getImageTimeBytes() {
      java.lang.Object ref = imageTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes imageName = 5;
    public static final int IMAGENAME_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString imageName_;
    /**
     * <code>optional bytes imageName = 5;</code>
     */
    public boolean hasImageName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes imageName = 5;</code>
     */
    public com.google.protobuf.ByteString getImageName() {
      return imageName_;
    }

    // optional uint64 length = 6;
    public static final int LENGTH_FIELD_NUMBER = 6;
    private long length_;
    /**
     * <code>optional uint64 length = 6;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint64 length = 6;</code>
     */
    public long getLength() {
      return length_;
    }

    private void initFields() {
      imageId_ = "";
      albumId_ = "";
      serverPath_ = com.google.protobuf.ByteString.EMPTY;
      imageTime_ = "";
      imageName_ = com.google.protobuf.ByteString.EMPTY;
      length_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getImageIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAlbumIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, serverPath_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getImageTimeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, imageName_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(6, length_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getImageIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAlbumIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, serverPath_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getImageTimeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, imageName_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, length_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.miapsoft.opq.proto.AlbumFile.AlbumFileProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.miapsoft.opq.proto.AlbumFile.AlbumFileProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.AlbumFile.AlbumFileProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.miapsoft.opq.proto.AlbumFile.AlbumFileProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.AlbumFile.AlbumFileProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.miapsoft.opq.proto.AlbumFile.AlbumFileProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.AlbumFile.AlbumFileProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.miapsoft.opq.proto.AlbumFile.AlbumFileProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.AlbumFile.AlbumFileProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.miapsoft.opq.proto.AlbumFile.AlbumFileProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.miapsoft.opq.proto.AlbumFile.AlbumFileProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.miapsoft.opq.proto.AlbumFileProto}
     *
     * <pre>
     *文件传输
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.miapsoft.opq.proto.AlbumFile.AlbumFileProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.miapsoft.opq.proto.AlbumFile.internal_static_com_miapsoft_opq_proto_AlbumFileProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.miapsoft.opq.proto.AlbumFile.internal_static_com_miapsoft_opq_proto_AlbumFileProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.miapsoft.opq.proto.AlbumFile.AlbumFileProto.class, com.miapsoft.opq.proto.AlbumFile.AlbumFileProto.Builder.class);
      }

      // Construct using com.miapsoft.opq.proto.AlbumFile.AlbumFileProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        imageId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        albumId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        serverPath_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        imageTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        imageName_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        length_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.miapsoft.opq.proto.AlbumFile.internal_static_com_miapsoft_opq_proto_AlbumFileProto_descriptor;
      }

      public com.miapsoft.opq.proto.AlbumFile.AlbumFileProto getDefaultInstanceForType() {
        return com.miapsoft.opq.proto.AlbumFile.AlbumFileProto.getDefaultInstance();
      }

      public com.miapsoft.opq.proto.AlbumFile.AlbumFileProto build() {
        com.miapsoft.opq.proto.AlbumFile.AlbumFileProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.miapsoft.opq.proto.AlbumFile.AlbumFileProto buildPartial() {
        com.miapsoft.opq.proto.AlbumFile.AlbumFileProto result = new com.miapsoft.opq.proto.AlbumFile.AlbumFileProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.imageId_ = imageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.albumId_ = albumId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serverPath_ = serverPath_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.imageTime_ = imageTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.imageName_ = imageName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.length_ = length_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.miapsoft.opq.proto.AlbumFile.AlbumFileProto) {
          return mergeFrom((com.miapsoft.opq.proto.AlbumFile.AlbumFileProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.miapsoft.opq.proto.AlbumFile.AlbumFileProto other) {
        if (other == com.miapsoft.opq.proto.AlbumFile.AlbumFileProto.getDefaultInstance()) return this;
        if (other.hasImageId()) {
          bitField0_ |= 0x00000001;
          imageId_ = other.imageId_;
          onChanged();
        }
        if (other.hasAlbumId()) {
          bitField0_ |= 0x00000002;
          albumId_ = other.albumId_;
          onChanged();
        }
        if (other.hasServerPath()) {
          setServerPath(other.getServerPath());
        }
        if (other.hasImageTime()) {
          bitField0_ |= 0x00000008;
          imageTime_ = other.imageTime_;
          onChanged();
        }
        if (other.hasImageName()) {
          setImageName(other.getImageName());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.miapsoft.opq.proto.AlbumFile.AlbumFileProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.miapsoft.opq.proto.AlbumFile.AlbumFileProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string imageId = 1;
      private java.lang.Object imageId_ = "";
      /**
       * <code>optional string imageId = 1;</code>
       */
      public boolean hasImageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string imageId = 1;</code>
       */
      public java.lang.String getImageId() {
        java.lang.Object ref = imageId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          imageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string imageId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getImageIdBytes() {
        java.lang.Object ref = imageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string imageId = 1;</code>
       */
      public Builder setImageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        imageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string imageId = 1;</code>
       */
      public Builder clearImageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        imageId_ = getDefaultInstance().getImageId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string imageId = 1;</code>
       */
      public Builder setImageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        imageId_ = value;
        onChanged();
        return this;
      }

      // optional string albumId = 2;
      private java.lang.Object albumId_ = "";
      /**
       * <code>optional string albumId = 2;</code>
       */
      public boolean hasAlbumId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string albumId = 2;</code>
       */
      public java.lang.String getAlbumId() {
        java.lang.Object ref = albumId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          albumId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string albumId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAlbumIdBytes() {
        java.lang.Object ref = albumId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          albumId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string albumId = 2;</code>
       */
      public Builder setAlbumId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        albumId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string albumId = 2;</code>
       */
      public Builder clearAlbumId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        albumId_ = getDefaultInstance().getAlbumId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string albumId = 2;</code>
       */
      public Builder setAlbumIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        albumId_ = value;
        onChanged();
        return this;
      }

      // optional bytes serverPath = 3;
      private com.google.protobuf.ByteString serverPath_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes serverPath = 3;</code>
       */
      public boolean hasServerPath() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes serverPath = 3;</code>
       */
      public com.google.protobuf.ByteString getServerPath() {
        return serverPath_;
      }
      /**
       * <code>optional bytes serverPath = 3;</code>
       */
      public Builder setServerPath(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serverPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes serverPath = 3;</code>
       */
      public Builder clearServerPath() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serverPath_ = getDefaultInstance().getServerPath();
        onChanged();
        return this;
      }

      // optional string imageTime = 4;
      private java.lang.Object imageTime_ = "";
      /**
       * <code>optional string imageTime = 4;</code>
       */
      public boolean hasImageTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string imageTime = 4;</code>
       */
      public java.lang.String getImageTime() {
        java.lang.Object ref = imageTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          imageTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string imageTime = 4;</code>
       */
      public com.google.protobuf.ByteString
          getImageTimeBytes() {
        java.lang.Object ref = imageTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string imageTime = 4;</code>
       */
      public Builder setImageTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        imageTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string imageTime = 4;</code>
       */
      public Builder clearImageTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        imageTime_ = getDefaultInstance().getImageTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string imageTime = 4;</code>
       */
      public Builder setImageTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        imageTime_ = value;
        onChanged();
        return this;
      }

      // optional bytes imageName = 5;
      private com.google.protobuf.ByteString imageName_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes imageName = 5;</code>
       */
      public boolean hasImageName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes imageName = 5;</code>
       */
      public com.google.protobuf.ByteString getImageName() {
        return imageName_;
      }
      /**
       * <code>optional bytes imageName = 5;</code>
       */
      public Builder setImageName(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        imageName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes imageName = 5;</code>
       */
      public Builder clearImageName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        imageName_ = getDefaultInstance().getImageName();
        onChanged();
        return this;
      }

      // optional uint64 length = 6;
      private long length_ ;
      /**
       * <code>optional uint64 length = 6;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint64 length = 6;</code>
       */
      public long getLength() {
        return length_;
      }
      /**
       * <code>optional uint64 length = 6;</code>
       */
      public Builder setLength(long value) {
        bitField0_ |= 0x00000020;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 length = 6;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000020);
        length_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.miapsoft.opq.proto.AlbumFileProto)
    }

    static {
      defaultInstance = new AlbumFileProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.miapsoft.opq.proto.AlbumFileProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_miapsoft_opq_proto_AlbumFileProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_miapsoft_opq_proto_AlbumFileProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017AlbumFile.proto\022\026com.miapsoft.opq.prot" +
      "o\"|\n\016AlbumFileProto\022\017\n\007imageId\030\001 \001(\t\022\017\n\007" +
      "albumId\030\002 \001(\t\022\022\n\nserverPath\030\003 \001(\014\022\021\n\tima" +
      "geTime\030\004 \001(\t\022\021\n\timageName\030\005 \001(\014\022\016\n\006lengt" +
      "h\030\006 \001(\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_miapsoft_opq_proto_AlbumFileProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_miapsoft_opq_proto_AlbumFileProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_miapsoft_opq_proto_AlbumFileProto_descriptor,
              new java.lang.String[] { "ImageId", "AlbumId", "ServerPath", "ImageTime", "ImageName", "Length", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
