// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Commentary.proto

package com.miapsoft.opq.proto;

public final class Commentary {
  private Commentary() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommentaryProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string id = 1;
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     *评论id
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     *评论id
     * </pre>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     *评论id
     * </pre>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // optional bytes msg = 2;
    /**
     * <code>optional bytes msg = 2;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    boolean hasMsg();
    /**
     * <code>optional bytes msg = 2;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    com.google.protobuf.ByteString getMsg();

    // optional string fromId = 3;
    /**
     * <code>optional string fromId = 3;</code>
     */
    boolean hasFromId();
    /**
     * <code>optional string fromId = 3;</code>
     */
    java.lang.String getFromId();
    /**
     * <code>optional string fromId = 3;</code>
     */
    com.google.protobuf.ByteString
        getFromIdBytes();

    // optional string toId = 4;
    /**
     * <code>optional string toId = 4;</code>
     */
    boolean hasToId();
    /**
     * <code>optional string toId = 4;</code>
     */
    java.lang.String getToId();
    /**
     * <code>optional string toId = 4;</code>
     */
    com.google.protobuf.ByteString
        getToIdBytes();

    // optional string talkId = 5;
    /**
     * <code>optional string talkId = 5;</code>
     */
    boolean hasTalkId();
    /**
     * <code>optional string talkId = 5;</code>
     */
    java.lang.String getTalkId();
    /**
     * <code>optional string talkId = 5;</code>
     */
    com.google.protobuf.ByteString
        getTalkIdBytes();

    // optional string commentTime = 6;
    /**
     * <code>optional string commentTime = 6;</code>
     */
    boolean hasCommentTime();
    /**
     * <code>optional string commentTime = 6;</code>
     */
    java.lang.String getCommentTime();
    /**
     * <code>optional string commentTime = 6;</code>
     */
    com.google.protobuf.ByteString
        getCommentTimeBytes();

    // optional bytes fromName = 7;
    /**
     * <code>optional bytes fromName = 7;</code>
     */
    boolean hasFromName();
    /**
     * <code>optional bytes fromName = 7;</code>
     */
    com.google.protobuf.ByteString getFromName();

    // optional bytes toName = 8;
    /**
     * <code>optional bytes toName = 8;</code>
     */
    boolean hasToName();
    /**
     * <code>optional bytes toName = 8;</code>
     */
    com.google.protobuf.ByteString getToName();
  }
  /**
   * Protobuf type {@code com.miapsoft.opq.proto.CommentaryProto}
   *
   * <pre>
   *评论
   * </pre>
   */
  public static final class CommentaryProto extends
      com.google.protobuf.GeneratedMessage
      implements CommentaryProtoOrBuilder {
    // Use CommentaryProto.newBuilder() to construct.
    private CommentaryProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CommentaryProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CommentaryProto defaultInstance;
    public static CommentaryProto getDefaultInstance() {
      return defaultInstance;
    }

    public CommentaryProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CommentaryProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msg_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              fromId_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              toId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              talkId_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              commentTime_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              fromName_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              toName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.miapsoft.opq.proto.Commentary.internal_static_com_miapsoft_opq_proto_CommentaryProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.miapsoft.opq.proto.Commentary.internal_static_com_miapsoft_opq_proto_CommentaryProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.miapsoft.opq.proto.Commentary.CommentaryProto.class, com.miapsoft.opq.proto.Commentary.CommentaryProto.Builder.class);
    }

    public static com.google.protobuf.Parser<CommentaryProto> PARSER =
        new com.google.protobuf.AbstractParser<CommentaryProto>() {
      public CommentaryProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommentaryProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CommentaryProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     *评论id
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     *评论id
     * </pre>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     *评论id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes msg = 2;
    public static final int MSG_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString msg_;
    /**
     * <code>optional bytes msg = 2;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes msg = 2;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    public com.google.protobuf.ByteString getMsg() {
      return msg_;
    }

    // optional string fromId = 3;
    public static final int FROMID_FIELD_NUMBER = 3;
    private java.lang.Object fromId_;
    /**
     * <code>optional string fromId = 3;</code>
     */
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string fromId = 3;</code>
     */
    public java.lang.String getFromId() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fromId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string toId = 4;
    public static final int TOID_FIELD_NUMBER = 4;
    private java.lang.Object toId_;
    /**
     * <code>optional string toId = 4;</code>
     */
    public boolean hasToId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string toId = 4;</code>
     */
    public java.lang.String getToId() {
      java.lang.Object ref = toId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string toId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getToIdBytes() {
      java.lang.Object ref = toId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string talkId = 5;
    public static final int TALKID_FIELD_NUMBER = 5;
    private java.lang.Object talkId_;
    /**
     * <code>optional string talkId = 5;</code>
     */
    public boolean hasTalkId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string talkId = 5;</code>
     */
    public java.lang.String getTalkId() {
      java.lang.Object ref = talkId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          talkId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string talkId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTalkIdBytes() {
      java.lang.Object ref = talkId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        talkId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string commentTime = 6;
    public static final int COMMENTTIME_FIELD_NUMBER = 6;
    private java.lang.Object commentTime_;
    /**
     * <code>optional string commentTime = 6;</code>
     */
    public boolean hasCommentTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string commentTime = 6;</code>
     */
    public java.lang.String getCommentTime() {
      java.lang.Object ref = commentTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          commentTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string commentTime = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCommentTimeBytes() {
      java.lang.Object ref = commentTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commentTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes fromName = 7;
    public static final int FROMNAME_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString fromName_;
    /**
     * <code>optional bytes fromName = 7;</code>
     */
    public boolean hasFromName() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bytes fromName = 7;</code>
     */
    public com.google.protobuf.ByteString getFromName() {
      return fromName_;
    }

    // optional bytes toName = 8;
    public static final int TONAME_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString toName_;
    /**
     * <code>optional bytes toName = 8;</code>
     */
    public boolean hasToName() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bytes toName = 8;</code>
     */
    public com.google.protobuf.ByteString getToName() {
      return toName_;
    }

    private void initFields() {
      id_ = "";
      msg_ = com.google.protobuf.ByteString.EMPTY;
      fromId_ = "";
      toId_ = "";
      talkId_ = "";
      commentTime_ = "";
      fromName_ = com.google.protobuf.ByteString.EMPTY;
      toName_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, msg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFromIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getToIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getTalkIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getCommentTimeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, fromName_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, toName_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, msg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFromIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getToIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getTalkIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getCommentTimeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, fromName_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, toName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.miapsoft.opq.proto.Commentary.CommentaryProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.miapsoft.opq.proto.Commentary.CommentaryProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.Commentary.CommentaryProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.miapsoft.opq.proto.Commentary.CommentaryProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.Commentary.CommentaryProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.miapsoft.opq.proto.Commentary.CommentaryProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.Commentary.CommentaryProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.miapsoft.opq.proto.Commentary.CommentaryProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.Commentary.CommentaryProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.miapsoft.opq.proto.Commentary.CommentaryProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.miapsoft.opq.proto.Commentary.CommentaryProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.miapsoft.opq.proto.CommentaryProto}
     *
     * <pre>
     *评论
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.miapsoft.opq.proto.Commentary.CommentaryProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.miapsoft.opq.proto.Commentary.internal_static_com_miapsoft_opq_proto_CommentaryProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.miapsoft.opq.proto.Commentary.internal_static_com_miapsoft_opq_proto_CommentaryProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.miapsoft.opq.proto.Commentary.CommentaryProto.class, com.miapsoft.opq.proto.Commentary.CommentaryProto.Builder.class);
      }

      // Construct using com.miapsoft.opq.proto.Commentary.CommentaryProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        fromId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        toId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        talkId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        commentTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        fromName_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        toName_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.miapsoft.opq.proto.Commentary.internal_static_com_miapsoft_opq_proto_CommentaryProto_descriptor;
      }

      public com.miapsoft.opq.proto.Commentary.CommentaryProto getDefaultInstanceForType() {
        return com.miapsoft.opq.proto.Commentary.CommentaryProto.getDefaultInstance();
      }

      public com.miapsoft.opq.proto.Commentary.CommentaryProto build() {
        com.miapsoft.opq.proto.Commentary.CommentaryProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.miapsoft.opq.proto.Commentary.CommentaryProto buildPartial() {
        com.miapsoft.opq.proto.Commentary.CommentaryProto result = new com.miapsoft.opq.proto.Commentary.CommentaryProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fromId_ = fromId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.toId_ = toId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.talkId_ = talkId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.commentTime_ = commentTime_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.fromName_ = fromName_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.toName_ = toName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.miapsoft.opq.proto.Commentary.CommentaryProto) {
          return mergeFrom((com.miapsoft.opq.proto.Commentary.CommentaryProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.miapsoft.opq.proto.Commentary.CommentaryProto other) {
        if (other == com.miapsoft.opq.proto.Commentary.CommentaryProto.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasMsg()) {
          setMsg(other.getMsg());
        }
        if (other.hasFromId()) {
          bitField0_ |= 0x00000004;
          fromId_ = other.fromId_;
          onChanged();
        }
        if (other.hasToId()) {
          bitField0_ |= 0x00000008;
          toId_ = other.toId_;
          onChanged();
        }
        if (other.hasTalkId()) {
          bitField0_ |= 0x00000010;
          talkId_ = other.talkId_;
          onChanged();
        }
        if (other.hasCommentTime()) {
          bitField0_ |= 0x00000020;
          commentTime_ = other.commentTime_;
          onChanged();
        }
        if (other.hasFromName()) {
          setFromName(other.getFromName());
        }
        if (other.hasToName()) {
          setToName(other.getToName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.miapsoft.opq.proto.Commentary.CommentaryProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.miapsoft.opq.proto.Commentary.CommentaryProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       *评论id
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       *评论id
       * </pre>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       *评论id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       *评论id
       * </pre>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       *评论id
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       *评论id
       * </pre>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // optional bytes msg = 2;
      private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes msg = 2;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes msg = 2;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public com.google.protobuf.ByteString getMsg() {
        return msg_;
      }
      /**
       * <code>optional bytes msg = 2;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public Builder setMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes msg = 2;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }

      // optional string fromId = 3;
      private java.lang.Object fromId_ = "";
      /**
       * <code>optional string fromId = 3;</code>
       */
      public boolean hasFromId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string fromId = 3;</code>
       */
      public java.lang.String getFromId() {
        java.lang.Object ref = fromId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fromId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fromId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFromIdBytes() {
        java.lang.Object ref = fromId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fromId = 3;</code>
       */
      public Builder setFromId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fromId = 3;</code>
       */
      public Builder clearFromId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fromId_ = getDefaultInstance().getFromId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fromId = 3;</code>
       */
      public Builder setFromIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fromId_ = value;
        onChanged();
        return this;
      }

      // optional string toId = 4;
      private java.lang.Object toId_ = "";
      /**
       * <code>optional string toId = 4;</code>
       */
      public boolean hasToId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string toId = 4;</code>
       */
      public java.lang.String getToId() {
        java.lang.Object ref = toId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          toId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string toId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getToIdBytes() {
        java.lang.Object ref = toId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string toId = 4;</code>
       */
      public Builder setToId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string toId = 4;</code>
       */
      public Builder clearToId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        toId_ = getDefaultInstance().getToId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string toId = 4;</code>
       */
      public Builder setToIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        toId_ = value;
        onChanged();
        return this;
      }

      // optional string talkId = 5;
      private java.lang.Object talkId_ = "";
      /**
       * <code>optional string talkId = 5;</code>
       */
      public boolean hasTalkId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string talkId = 5;</code>
       */
      public java.lang.String getTalkId() {
        java.lang.Object ref = talkId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          talkId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string talkId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTalkIdBytes() {
        java.lang.Object ref = talkId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          talkId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string talkId = 5;</code>
       */
      public Builder setTalkId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        talkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string talkId = 5;</code>
       */
      public Builder clearTalkId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        talkId_ = getDefaultInstance().getTalkId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string talkId = 5;</code>
       */
      public Builder setTalkIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        talkId_ = value;
        onChanged();
        return this;
      }

      // optional string commentTime = 6;
      private java.lang.Object commentTime_ = "";
      /**
       * <code>optional string commentTime = 6;</code>
       */
      public boolean hasCommentTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string commentTime = 6;</code>
       */
      public java.lang.String getCommentTime() {
        java.lang.Object ref = commentTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          commentTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string commentTime = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCommentTimeBytes() {
        java.lang.Object ref = commentTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commentTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string commentTime = 6;</code>
       */
      public Builder setCommentTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        commentTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string commentTime = 6;</code>
       */
      public Builder clearCommentTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        commentTime_ = getDefaultInstance().getCommentTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string commentTime = 6;</code>
       */
      public Builder setCommentTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        commentTime_ = value;
        onChanged();
        return this;
      }

      // optional bytes fromName = 7;
      private com.google.protobuf.ByteString fromName_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes fromName = 7;</code>
       */
      public boolean hasFromName() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes fromName = 7;</code>
       */
      public com.google.protobuf.ByteString getFromName() {
        return fromName_;
      }
      /**
       * <code>optional bytes fromName = 7;</code>
       */
      public Builder setFromName(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        fromName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes fromName = 7;</code>
       */
      public Builder clearFromName() {
        bitField0_ = (bitField0_ & ~0x00000040);
        fromName_ = getDefaultInstance().getFromName();
        onChanged();
        return this;
      }

      // optional bytes toName = 8;
      private com.google.protobuf.ByteString toName_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes toName = 8;</code>
       */
      public boolean hasToName() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bytes toName = 8;</code>
       */
      public com.google.protobuf.ByteString getToName() {
        return toName_;
      }
      /**
       * <code>optional bytes toName = 8;</code>
       */
      public Builder setToName(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        toName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes toName = 8;</code>
       */
      public Builder clearToName() {
        bitField0_ = (bitField0_ & ~0x00000080);
        toName_ = getDefaultInstance().getToName();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.miapsoft.opq.proto.CommentaryProto)
    }

    static {
      defaultInstance = new CommentaryProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.miapsoft.opq.proto.CommentaryProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_miapsoft_opq_proto_CommentaryProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_miapsoft_opq_proto_CommentaryProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Commentary.proto\022\026com.miapsoft.opq.pro" +
      "to\"\217\001\n\017CommentaryProto\022\n\n\002id\030\001 \001(\t\022\013\n\003ms" +
      "g\030\002 \001(\014\022\016\n\006fromId\030\003 \001(\t\022\014\n\004toId\030\004 \001(\t\022\016\n" +
      "\006talkId\030\005 \001(\t\022\023\n\013commentTime\030\006 \001(\t\022\020\n\010fr" +
      "omName\030\007 \001(\014\022\016\n\006toName\030\010 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_miapsoft_opq_proto_CommentaryProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_miapsoft_opq_proto_CommentaryProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_miapsoft_opq_proto_CommentaryProto_descriptor,
              new java.lang.String[] { "Id", "Msg", "FromId", "ToId", "TalkId", "CommentTime", "FromName", "ToName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
