// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileTransfer.proto

package com.miapsoft.opq.proto;

public final class FileTransfer {
  private FileTransfer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FileTransferProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes filePath = 1;
    /**
     * <code>required bytes filePath = 1;</code>
     */
    boolean hasFilePath();
    /**
     * <code>required bytes filePath = 1;</code>
     */
    com.google.protobuf.ByteString getFilePath();

    // required bytes serverPath = 2;
    /**
     * <code>required bytes serverPath = 2;</code>
     */
    boolean hasServerPath();
    /**
     * <code>required bytes serverPath = 2;</code>
     */
    com.google.protobuf.ByteString getServerPath();

    // required uint64 offset = 3;
    /**
     * <code>required uint64 offset = 3;</code>
     */
    boolean hasOffset();
    /**
     * <code>required uint64 offset = 3;</code>
     */
    long getOffset();

    // optional bytes data = 4;
    /**
     * <code>optional bytes data = 4;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 4;</code>
     */
    com.google.protobuf.ByteString getData();

    // optional string fileId = 5;
    /**
     * <code>optional string fileId = 5;</code>
     */
    boolean hasFileId();
    /**
     * <code>optional string fileId = 5;</code>
     */
    java.lang.String getFileId();
    /**
     * <code>optional string fileId = 5;</code>
     */
    com.google.protobuf.ByteString
        getFileIdBytes();

    // optional uint64 length = 6;
    /**
     * <code>optional uint64 length = 6;</code>
     */
    boolean hasLength();
    /**
     * <code>optional uint64 length = 6;</code>
     */
    long getLength();

    // optional string fromId = 7;
    /**
     * <code>optional string fromId = 7;</code>
     */
    boolean hasFromId();
    /**
     * <code>optional string fromId = 7;</code>
     */
    java.lang.String getFromId();
    /**
     * <code>optional string fromId = 7;</code>
     */
    com.google.protobuf.ByteString
        getFromIdBytes();

    // optional string toId = 8;
    /**
     * <code>optional string toId = 8;</code>
     */
    boolean hasToId();
    /**
     * <code>optional string toId = 8;</code>
     */
    java.lang.String getToId();
    /**
     * <code>optional string toId = 8;</code>
     */
    com.google.protobuf.ByteString
        getToIdBytes();
  }
  /**
   * Protobuf type {@code com.miapsoft.opq.proto.FileTransferProto}
   *
   * <pre>
   *文件传输
   * </pre>
   */
  public static final class FileTransferProto extends
      com.google.protobuf.GeneratedMessage
      implements FileTransferProtoOrBuilder {
    // Use FileTransferProto.newBuilder() to construct.
    private FileTransferProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FileTransferProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FileTransferProto defaultInstance;
    public static FileTransferProto getDefaultInstance() {
      return defaultInstance;
    }

    public FileTransferProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FileTransferProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              filePath_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              serverPath_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              offset_ = input.readUInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              data_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              fileId_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              length_ = input.readUInt64();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              fromId_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              toId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.miapsoft.opq.proto.FileTransfer.internal_static_com_miapsoft_opq_proto_FileTransferProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.miapsoft.opq.proto.FileTransfer.internal_static_com_miapsoft_opq_proto_FileTransferProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.miapsoft.opq.proto.FileTransfer.FileTransferProto.class, com.miapsoft.opq.proto.FileTransfer.FileTransferProto.Builder.class);
    }

    public static com.google.protobuf.Parser<FileTransferProto> PARSER =
        new com.google.protobuf.AbstractParser<FileTransferProto>() {
      public FileTransferProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileTransferProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FileTransferProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes filePath = 1;
    public static final int FILEPATH_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString filePath_;
    /**
     * <code>required bytes filePath = 1;</code>
     */
    public boolean hasFilePath() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes filePath = 1;</code>
     */
    public com.google.protobuf.ByteString getFilePath() {
      return filePath_;
    }

    // required bytes serverPath = 2;
    public static final int SERVERPATH_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString serverPath_;
    /**
     * <code>required bytes serverPath = 2;</code>
     */
    public boolean hasServerPath() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes serverPath = 2;</code>
     */
    public com.google.protobuf.ByteString getServerPath() {
      return serverPath_;
    }

    // required uint64 offset = 3;
    public static final int OFFSET_FIELD_NUMBER = 3;
    private long offset_;
    /**
     * <code>required uint64 offset = 3;</code>
     */
    public boolean hasOffset() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint64 offset = 3;</code>
     */
    public long getOffset() {
      return offset_;
    }

    // optional bytes data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 4;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes data = 4;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    // optional string fileId = 5;
    public static final int FILEID_FIELD_NUMBER = 5;
    private java.lang.Object fileId_;
    /**
     * <code>optional string fileId = 5;</code>
     */
    public boolean hasFileId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string fileId = 5;</code>
     */
    public java.lang.String getFileId() {
      java.lang.Object ref = fileId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fileId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFileIdBytes() {
      java.lang.Object ref = fileId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint64 length = 6;
    public static final int LENGTH_FIELD_NUMBER = 6;
    private long length_;
    /**
     * <code>optional uint64 length = 6;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint64 length = 6;</code>
     */
    public long getLength() {
      return length_;
    }

    // optional string fromId = 7;
    public static final int FROMID_FIELD_NUMBER = 7;
    private java.lang.Object fromId_;
    /**
     * <code>optional string fromId = 7;</code>
     */
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string fromId = 7;</code>
     */
    public java.lang.String getFromId() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fromId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string toId = 8;
    public static final int TOID_FIELD_NUMBER = 8;
    private java.lang.Object toId_;
    /**
     * <code>optional string toId = 8;</code>
     */
    public boolean hasToId() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string toId = 8;</code>
     */
    public java.lang.String getToId() {
      java.lang.Object ref = toId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string toId = 8;</code>
     */
    public com.google.protobuf.ByteString
        getToIdBytes() {
      java.lang.Object ref = toId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      filePath_ = com.google.protobuf.ByteString.EMPTY;
      serverPath_ = com.google.protobuf.ByteString.EMPTY;
      offset_ = 0L;
      data_ = com.google.protobuf.ByteString.EMPTY;
      fileId_ = "";
      length_ = 0L;
      fromId_ = "";
      toId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFilePath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerPath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOffset()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, filePath_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, serverPath_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, offset_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, data_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getFileIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(6, length_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getFromIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getToIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, filePath_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, serverPath_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, offset_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getFileIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, length_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getFromIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getToIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.miapsoft.opq.proto.FileTransfer.FileTransferProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.miapsoft.opq.proto.FileTransfer.FileTransferProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.FileTransfer.FileTransferProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.miapsoft.opq.proto.FileTransfer.FileTransferProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.FileTransfer.FileTransferProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.miapsoft.opq.proto.FileTransfer.FileTransferProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.FileTransfer.FileTransferProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.miapsoft.opq.proto.FileTransfer.FileTransferProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.FileTransfer.FileTransferProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.miapsoft.opq.proto.FileTransfer.FileTransferProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.miapsoft.opq.proto.FileTransfer.FileTransferProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.miapsoft.opq.proto.FileTransferProto}
     *
     * <pre>
     *文件传输
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.miapsoft.opq.proto.FileTransfer.FileTransferProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.miapsoft.opq.proto.FileTransfer.internal_static_com_miapsoft_opq_proto_FileTransferProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.miapsoft.opq.proto.FileTransfer.internal_static_com_miapsoft_opq_proto_FileTransferProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.miapsoft.opq.proto.FileTransfer.FileTransferProto.class, com.miapsoft.opq.proto.FileTransfer.FileTransferProto.Builder.class);
      }

      // Construct using com.miapsoft.opq.proto.FileTransfer.FileTransferProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        filePath_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        serverPath_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        offset_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        fileId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        length_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        fromId_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        toId_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.miapsoft.opq.proto.FileTransfer.internal_static_com_miapsoft_opq_proto_FileTransferProto_descriptor;
      }

      public com.miapsoft.opq.proto.FileTransfer.FileTransferProto getDefaultInstanceForType() {
        return com.miapsoft.opq.proto.FileTransfer.FileTransferProto.getDefaultInstance();
      }

      public com.miapsoft.opq.proto.FileTransfer.FileTransferProto build() {
        com.miapsoft.opq.proto.FileTransfer.FileTransferProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.miapsoft.opq.proto.FileTransfer.FileTransferProto buildPartial() {
        com.miapsoft.opq.proto.FileTransfer.FileTransferProto result = new com.miapsoft.opq.proto.FileTransfer.FileTransferProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.filePath_ = filePath_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serverPath_ = serverPath_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.offset_ = offset_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.fileId_ = fileId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.fromId_ = fromId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.toId_ = toId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.miapsoft.opq.proto.FileTransfer.FileTransferProto) {
          return mergeFrom((com.miapsoft.opq.proto.FileTransfer.FileTransferProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.miapsoft.opq.proto.FileTransfer.FileTransferProto other) {
        if (other == com.miapsoft.opq.proto.FileTransfer.FileTransferProto.getDefaultInstance()) return this;
        if (other.hasFilePath()) {
          setFilePath(other.getFilePath());
        }
        if (other.hasServerPath()) {
          setServerPath(other.getServerPath());
        }
        if (other.hasOffset()) {
          setOffset(other.getOffset());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasFileId()) {
          bitField0_ |= 0x00000010;
          fileId_ = other.fileId_;
          onChanged();
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasFromId()) {
          bitField0_ |= 0x00000040;
          fromId_ = other.fromId_;
          onChanged();
        }
        if (other.hasToId()) {
          bitField0_ |= 0x00000080;
          toId_ = other.toId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFilePath()) {
          
          return false;
        }
        if (!hasServerPath()) {
          
          return false;
        }
        if (!hasOffset()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.miapsoft.opq.proto.FileTransfer.FileTransferProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.miapsoft.opq.proto.FileTransfer.FileTransferProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes filePath = 1;
      private com.google.protobuf.ByteString filePath_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes filePath = 1;</code>
       */
      public boolean hasFilePath() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes filePath = 1;</code>
       */
      public com.google.protobuf.ByteString getFilePath() {
        return filePath_;
      }
      /**
       * <code>required bytes filePath = 1;</code>
       */
      public Builder setFilePath(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes filePath = 1;</code>
       */
      public Builder clearFilePath() {
        bitField0_ = (bitField0_ & ~0x00000001);
        filePath_ = getDefaultInstance().getFilePath();
        onChanged();
        return this;
      }

      // required bytes serverPath = 2;
      private com.google.protobuf.ByteString serverPath_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes serverPath = 2;</code>
       */
      public boolean hasServerPath() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes serverPath = 2;</code>
       */
      public com.google.protobuf.ByteString getServerPath() {
        return serverPath_;
      }
      /**
       * <code>required bytes serverPath = 2;</code>
       */
      public Builder setServerPath(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        serverPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes serverPath = 2;</code>
       */
      public Builder clearServerPath() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverPath_ = getDefaultInstance().getServerPath();
        onChanged();
        return this;
      }

      // required uint64 offset = 3;
      private long offset_ ;
      /**
       * <code>required uint64 offset = 3;</code>
       */
      public boolean hasOffset() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint64 offset = 3;</code>
       */
      public long getOffset() {
        return offset_;
      }
      /**
       * <code>required uint64 offset = 3;</code>
       */
      public Builder setOffset(long value) {
        bitField0_ |= 0x00000004;
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 offset = 3;</code>
       */
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000004);
        offset_ = 0L;
        onChanged();
        return this;
      }

      // optional bytes data = 4;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 4;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes data = 4;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 4;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 4;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // optional string fileId = 5;
      private java.lang.Object fileId_ = "";
      /**
       * <code>optional string fileId = 5;</code>
       */
      public boolean hasFileId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string fileId = 5;</code>
       */
      public java.lang.String getFileId() {
        java.lang.Object ref = fileId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fileId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fileId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFileIdBytes() {
        java.lang.Object ref = fileId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fileId = 5;</code>
       */
      public Builder setFileId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        fileId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileId = 5;</code>
       */
      public Builder clearFileId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fileId_ = getDefaultInstance().getFileId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileId = 5;</code>
       */
      public Builder setFileIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        fileId_ = value;
        onChanged();
        return this;
      }

      // optional uint64 length = 6;
      private long length_ ;
      /**
       * <code>optional uint64 length = 6;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint64 length = 6;</code>
       */
      public long getLength() {
        return length_;
      }
      /**
       * <code>optional uint64 length = 6;</code>
       */
      public Builder setLength(long value) {
        bitField0_ |= 0x00000020;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 length = 6;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000020);
        length_ = 0L;
        onChanged();
        return this;
      }

      // optional string fromId = 7;
      private java.lang.Object fromId_ = "";
      /**
       * <code>optional string fromId = 7;</code>
       */
      public boolean hasFromId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string fromId = 7;</code>
       */
      public java.lang.String getFromId() {
        java.lang.Object ref = fromId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fromId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fromId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getFromIdBytes() {
        java.lang.Object ref = fromId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fromId = 7;</code>
       */
      public Builder setFromId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fromId = 7;</code>
       */
      public Builder clearFromId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        fromId_ = getDefaultInstance().getFromId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fromId = 7;</code>
       */
      public Builder setFromIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        fromId_ = value;
        onChanged();
        return this;
      }

      // optional string toId = 8;
      private java.lang.Object toId_ = "";
      /**
       * <code>optional string toId = 8;</code>
       */
      public boolean hasToId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string toId = 8;</code>
       */
      public java.lang.String getToId() {
        java.lang.Object ref = toId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          toId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string toId = 8;</code>
       */
      public com.google.protobuf.ByteString
          getToIdBytes() {
        java.lang.Object ref = toId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string toId = 8;</code>
       */
      public Builder setToId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string toId = 8;</code>
       */
      public Builder clearToId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        toId_ = getDefaultInstance().getToId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string toId = 8;</code>
       */
      public Builder setToIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        toId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.miapsoft.opq.proto.FileTransferProto)
    }

    static {
      defaultInstance = new FileTransferProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.miapsoft.opq.proto.FileTransferProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_miapsoft_opq_proto_FileTransferProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_miapsoft_opq_proto_FileTransferProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022FileTransfer.proto\022\026com.miapsoft.opq.p" +
      "roto\"\225\001\n\021FileTransferProto\022\020\n\010filePath\030\001" +
      " \002(\014\022\022\n\nserverPath\030\002 \002(\014\022\016\n\006offset\030\003 \002(\004" +
      "\022\014\n\004data\030\004 \001(\014\022\016\n\006fileId\030\005 \001(\t\022\016\n\006length" +
      "\030\006 \001(\004\022\016\n\006fromId\030\007 \001(\t\022\014\n\004toId\030\010 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_miapsoft_opq_proto_FileTransferProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_miapsoft_opq_proto_FileTransferProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_miapsoft_opq_proto_FileTransferProto_descriptor,
              new java.lang.String[] { "FilePath", "ServerPath", "Offset", "Data", "FileId", "Length", "FromId", "ToId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
