// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Talk.proto

package com.miapsoft.opq.proto;

public final class Talk {
  private Talk() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TalkProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string fromId = 1;
    /**
     * <code>required string fromId = 1;</code>
     */
    boolean hasFromId();
    /**
     * <code>required string fromId = 1;</code>
     */
    java.lang.String getFromId();
    /**
     * <code>required string fromId = 1;</code>
     */
    com.google.protobuf.ByteString
        getFromIdBytes();

    // optional string talkId = 2;
    /**
     * <code>optional string talkId = 2;</code>
     */
    boolean hasTalkId();
    /**
     * <code>optional string talkId = 2;</code>
     */
    java.lang.String getTalkId();
    /**
     * <code>optional string talkId = 2;</code>
     */
    com.google.protobuf.ByteString
        getTalkIdBytes();

    // optional bytes msg = 3;
    /**
     * <code>optional bytes msg = 3;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional bytes msg = 3;</code>
     */
    com.google.protobuf.ByteString getMsg();

    // optional string talkTime = 4;
    /**
     * <code>optional string talkTime = 4;</code>
     */
    boolean hasTalkTime();
    /**
     * <code>optional string talkTime = 4;</code>
     */
    java.lang.String getTalkTime();
    /**
     * <code>optional string talkTime = 4;</code>
     */
    com.google.protobuf.ByteString
        getTalkTimeBytes();

    // repeated bytes commentary = 5;
    /**
     * <code>repeated bytes commentary = 5;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getCommentaryList();
    /**
     * <code>repeated bytes commentary = 5;</code>
     */
    int getCommentaryCount();
    /**
     * <code>repeated bytes commentary = 5;</code>
     */
    com.google.protobuf.ByteString getCommentary(int index);
  }
  /**
   * Protobuf type {@code com.miapsoft.opq.proto.TalkProto}
   *
   * <pre>
   *˵˵
   * </pre>
   */
  public static final class TalkProto extends
      com.google.protobuf.GeneratedMessage
      implements TalkProtoOrBuilder {
    // Use TalkProto.newBuilder() to construct.
    private TalkProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TalkProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TalkProto defaultInstance;
    public static TalkProto getDefaultInstance() {
      return defaultInstance;
    }

    public TalkProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TalkProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fromId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              talkId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              msg_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              talkTime_ = input.readBytes();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                commentary_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000010;
              }
              commentary_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          commentary_ = java.util.Collections.unmodifiableList(commentary_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.miapsoft.opq.proto.Talk.internal_static_com_miapsoft_opq_proto_TalkProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.miapsoft.opq.proto.Talk.internal_static_com_miapsoft_opq_proto_TalkProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.miapsoft.opq.proto.Talk.TalkProto.class, com.miapsoft.opq.proto.Talk.TalkProto.Builder.class);
    }

    public static com.google.protobuf.Parser<TalkProto> PARSER =
        new com.google.protobuf.AbstractParser<TalkProto>() {
      public TalkProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TalkProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TalkProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string fromId = 1;
    public static final int FROMID_FIELD_NUMBER = 1;
    private java.lang.Object fromId_;
    /**
     * <code>required string fromId = 1;</code>
     */
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string fromId = 1;</code>
     */
    public java.lang.String getFromId() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fromId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string talkId = 2;
    public static final int TALKID_FIELD_NUMBER = 2;
    private java.lang.Object talkId_;
    /**
     * <code>optional string talkId = 2;</code>
     */
    public boolean hasTalkId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string talkId = 2;</code>
     */
    public java.lang.String getTalkId() {
      java.lang.Object ref = talkId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          talkId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string talkId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTalkIdBytes() {
      java.lang.Object ref = talkId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        talkId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes msg = 3;
    public static final int MSG_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString msg_;
    /**
     * <code>optional bytes msg = 3;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes msg = 3;</code>
     */
    public com.google.protobuf.ByteString getMsg() {
      return msg_;
    }

    // optional string talkTime = 4;
    public static final int TALKTIME_FIELD_NUMBER = 4;
    private java.lang.Object talkTime_;
    /**
     * <code>optional string talkTime = 4;</code>
     */
    public boolean hasTalkTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string talkTime = 4;</code>
     */
    public java.lang.String getTalkTime() {
      java.lang.Object ref = talkTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          talkTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string talkTime = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTalkTimeBytes() {
      java.lang.Object ref = talkTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        talkTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated bytes commentary = 5;
    public static final int COMMENTARY_FIELD_NUMBER = 5;
    private java.util.List<com.google.protobuf.ByteString> commentary_;
    /**
     * <code>repeated bytes commentary = 5;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getCommentaryList() {
      return commentary_;
    }
    /**
     * <code>repeated bytes commentary = 5;</code>
     */
    public int getCommentaryCount() {
      return commentary_.size();
    }
    /**
     * <code>repeated bytes commentary = 5;</code>
     */
    public com.google.protobuf.ByteString getCommentary(int index) {
      return commentary_.get(index);
    }

    private void initFields() {
      fromId_ = "";
      talkId_ = "";
      msg_ = com.google.protobuf.ByteString.EMPTY;
      talkTime_ = "";
      commentary_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFromId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFromIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTalkIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, msg_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTalkTimeBytes());
      }
      for (int i = 0; i < commentary_.size(); i++) {
        output.writeBytes(5, commentary_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFromIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTalkIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, msg_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTalkTimeBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < commentary_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(commentary_.get(i));
        }
        size += dataSize;
        size += 1 * getCommentaryList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.miapsoft.opq.proto.Talk.TalkProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.miapsoft.opq.proto.Talk.TalkProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.Talk.TalkProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.miapsoft.opq.proto.Talk.TalkProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.Talk.TalkProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.miapsoft.opq.proto.Talk.TalkProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.Talk.TalkProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.miapsoft.opq.proto.Talk.TalkProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.Talk.TalkProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.miapsoft.opq.proto.Talk.TalkProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.miapsoft.opq.proto.Talk.TalkProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.miapsoft.opq.proto.TalkProto}
     *
     * <pre>
     *˵˵
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.miapsoft.opq.proto.Talk.TalkProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.miapsoft.opq.proto.Talk.internal_static_com_miapsoft_opq_proto_TalkProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.miapsoft.opq.proto.Talk.internal_static_com_miapsoft_opq_proto_TalkProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.miapsoft.opq.proto.Talk.TalkProto.class, com.miapsoft.opq.proto.Talk.TalkProto.Builder.class);
      }

      // Construct using com.miapsoft.opq.proto.Talk.TalkProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fromId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        talkId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        talkTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        commentary_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.miapsoft.opq.proto.Talk.internal_static_com_miapsoft_opq_proto_TalkProto_descriptor;
      }

      public com.miapsoft.opq.proto.Talk.TalkProto getDefaultInstanceForType() {
        return com.miapsoft.opq.proto.Talk.TalkProto.getDefaultInstance();
      }

      public com.miapsoft.opq.proto.Talk.TalkProto build() {
        com.miapsoft.opq.proto.Talk.TalkProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.miapsoft.opq.proto.Talk.TalkProto buildPartial() {
        com.miapsoft.opq.proto.Talk.TalkProto result = new com.miapsoft.opq.proto.Talk.TalkProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fromId_ = fromId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.talkId_ = talkId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.talkTime_ = talkTime_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          commentary_ = java.util.Collections.unmodifiableList(commentary_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.commentary_ = commentary_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.miapsoft.opq.proto.Talk.TalkProto) {
          return mergeFrom((com.miapsoft.opq.proto.Talk.TalkProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.miapsoft.opq.proto.Talk.TalkProto other) {
        if (other == com.miapsoft.opq.proto.Talk.TalkProto.getDefaultInstance()) return this;
        if (other.hasFromId()) {
          bitField0_ |= 0x00000001;
          fromId_ = other.fromId_;
          onChanged();
        }
        if (other.hasTalkId()) {
          bitField0_ |= 0x00000002;
          talkId_ = other.talkId_;
          onChanged();
        }
        if (other.hasMsg()) {
          setMsg(other.getMsg());
        }
        if (other.hasTalkTime()) {
          bitField0_ |= 0x00000008;
          talkTime_ = other.talkTime_;
          onChanged();
        }
        if (!other.commentary_.isEmpty()) {
          if (commentary_.isEmpty()) {
            commentary_ = other.commentary_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureCommentaryIsMutable();
            commentary_.addAll(other.commentary_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFromId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.miapsoft.opq.proto.Talk.TalkProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.miapsoft.opq.proto.Talk.TalkProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string fromId = 1;
      private java.lang.Object fromId_ = "";
      /**
       * <code>required string fromId = 1;</code>
       */
      public boolean hasFromId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string fromId = 1;</code>
       */
      public java.lang.String getFromId() {
        java.lang.Object ref = fromId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fromId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fromId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFromIdBytes() {
        java.lang.Object ref = fromId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fromId = 1;</code>
       */
      public Builder setFromId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fromId = 1;</code>
       */
      public Builder clearFromId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromId_ = getDefaultInstance().getFromId();
        onChanged();
        return this;
      }
      /**
       * <code>required string fromId = 1;</code>
       */
      public Builder setFromIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fromId_ = value;
        onChanged();
        return this;
      }

      // optional string talkId = 2;
      private java.lang.Object talkId_ = "";
      /**
       * <code>optional string talkId = 2;</code>
       */
      public boolean hasTalkId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string talkId = 2;</code>
       */
      public java.lang.String getTalkId() {
        java.lang.Object ref = talkId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          talkId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string talkId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTalkIdBytes() {
        java.lang.Object ref = talkId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          talkId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string talkId = 2;</code>
       */
      public Builder setTalkId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        talkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string talkId = 2;</code>
       */
      public Builder clearTalkId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        talkId_ = getDefaultInstance().getTalkId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string talkId = 2;</code>
       */
      public Builder setTalkIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        talkId_ = value;
        onChanged();
        return this;
      }

      // optional bytes msg = 3;
      private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes msg = 3;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes msg = 3;</code>
       */
      public com.google.protobuf.ByteString getMsg() {
        return msg_;
      }
      /**
       * <code>optional bytes msg = 3;</code>
       */
      public Builder setMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes msg = 3;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }

      // optional string talkTime = 4;
      private java.lang.Object talkTime_ = "";
      /**
       * <code>optional string talkTime = 4;</code>
       */
      public boolean hasTalkTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string talkTime = 4;</code>
       */
      public java.lang.String getTalkTime() {
        java.lang.Object ref = talkTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          talkTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string talkTime = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTalkTimeBytes() {
        java.lang.Object ref = talkTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          talkTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string talkTime = 4;</code>
       */
      public Builder setTalkTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        talkTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string talkTime = 4;</code>
       */
      public Builder clearTalkTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        talkTime_ = getDefaultInstance().getTalkTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string talkTime = 4;</code>
       */
      public Builder setTalkTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        talkTime_ = value;
        onChanged();
        return this;
      }

      // repeated bytes commentary = 5;
      private java.util.List<com.google.protobuf.ByteString> commentary_ = java.util.Collections.emptyList();
      private void ensureCommentaryIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          commentary_ = new java.util.ArrayList<com.google.protobuf.ByteString>(commentary_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated bytes commentary = 5;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getCommentaryList() {
        return java.util.Collections.unmodifiableList(commentary_);
      }
      /**
       * <code>repeated bytes commentary = 5;</code>
       */
      public int getCommentaryCount() {
        return commentary_.size();
      }
      /**
       * <code>repeated bytes commentary = 5;</code>
       */
      public com.google.protobuf.ByteString getCommentary(int index) {
        return commentary_.get(index);
      }
      /**
       * <code>repeated bytes commentary = 5;</code>
       */
      public Builder setCommentary(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCommentaryIsMutable();
        commentary_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes commentary = 5;</code>
       */
      public Builder addCommentary(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCommentaryIsMutable();
        commentary_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes commentary = 5;</code>
       */
      public Builder addAllCommentary(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureCommentaryIsMutable();
        super.addAll(values, commentary_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes commentary = 5;</code>
       */
      public Builder clearCommentary() {
        commentary_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.miapsoft.opq.proto.TalkProto)
    }

    static {
      defaultInstance = new TalkProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.miapsoft.opq.proto.TalkProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_miapsoft_opq_proto_TalkProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_miapsoft_opq_proto_TalkProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTalk.proto\022\026com.miapsoft.opq.proto\"^\n\t" +
      "TalkProto\022\016\n\006fromId\030\001 \002(\t\022\016\n\006talkId\030\002 \001(" +
      "\t\022\013\n\003msg\030\003 \001(\014\022\020\n\010talkTime\030\004 \001(\t\022\022\n\ncomm" +
      "entary\030\005 \003(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_miapsoft_opq_proto_TalkProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_miapsoft_opq_proto_TalkProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_miapsoft_opq_proto_TalkProto_descriptor,
              new java.lang.String[] { "FromId", "TalkId", "Msg", "TalkTime", "Commentary", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
