// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserInfo.proto

package com.miapsoft.opq.proto;

public final class UserInfo {
  private UserInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserInfoProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string id = 1;
    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // optional bytes name = 2;
    /**
     * <code>optional bytes name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional bytes name = 2;</code>
     */
    com.google.protobuf.ByteString getName();

    // optional bytes headerImg = 3;
    /**
     * <code>optional bytes headerImg = 3;</code>
     */
    boolean hasHeaderImg();
    /**
     * <code>optional bytes headerImg = 3;</code>
     */
    com.google.protobuf.ByteString getHeaderImg();

    // optional int32 sex = 4;
    /**
     * <code>optional int32 sex = 4;</code>
     */
    boolean hasSex();
    /**
     * <code>optional int32 sex = 4;</code>
     */
    int getSex();

    // optional bytes position = 5;
    /**
     * <code>optional bytes position = 5;</code>
     *
     * <pre>
     *地区
     * </pre>
     */
    boolean hasPosition();
    /**
     * <code>optional bytes position = 5;</code>
     *
     * <pre>
     *地区
     * </pre>
     */
    com.google.protobuf.ByteString getPosition();

    // optional bytes address = 6;
    /**
     * <code>optional bytes address = 6;</code>
     *
     * <pre>
     *地址
     * </pre>
     */
    boolean hasAddress();
    /**
     * <code>optional bytes address = 6;</code>
     *
     * <pre>
     *地址
     * </pre>
     */
    com.google.protobuf.ByteString getAddress();

    // optional bytes motto = 7;
    /**
     * <code>optional bytes motto = 7;</code>
     *
     * <pre>
     *个性签名
     * </pre>
     */
    boolean hasMotto();
    /**
     * <code>optional bytes motto = 7;</code>
     *
     * <pre>
     *个性签名
     * </pre>
     */
    com.google.protobuf.ByteString getMotto();

    // optional bytes nameRemark = 8;
    /**
     * <code>optional bytes nameRemark = 8;</code>
     *
     * <pre>
     *备注
     * </pre>
     */
    boolean hasNameRemark();
    /**
     * <code>optional bytes nameRemark = 8;</code>
     *
     * <pre>
     *备注
     * </pre>
     */
    com.google.protobuf.ByteString getNameRemark();

    // optional string pwd = 9;
    /**
     * <code>optional string pwd = 9;</code>
     */
    boolean hasPwd();
    /**
     * <code>optional string pwd = 9;</code>
     */
    java.lang.String getPwd();
    /**
     * <code>optional string pwd = 9;</code>
     */
    com.google.protobuf.ByteString
        getPwdBytes();

    // optional string birthday = 10;
    /**
     * <code>optional string birthday = 10;</code>
     */
    boolean hasBirthday();
    /**
     * <code>optional string birthday = 10;</code>
     */
    java.lang.String getBirthday();
    /**
     * <code>optional string birthday = 10;</code>
     */
    com.google.protobuf.ByteString
        getBirthdayBytes();

    // optional string email = 11;
    /**
     * <code>optional string email = 11;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 11;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 11;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // optional string phone = 12;
    /**
     * <code>optional string phone = 12;</code>
     */
    boolean hasPhone();
    /**
     * <code>optional string phone = 12;</code>
     */
    java.lang.String getPhone();
    /**
     * <code>optional string phone = 12;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();
  }
  /**
   * Protobuf type {@code com.miapsoft.opq.proto.UserInfoProto}
   *
   * <pre>
   *用户信息
   * </pre>
   */
  public static final class UserInfoProto extends
      com.google.protobuf.GeneratedMessage
      implements UserInfoProtoOrBuilder {
    // Use UserInfoProto.newBuilder() to construct.
    private UserInfoProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserInfoProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserInfoProto defaultInstance;
    public static UserInfoProto getDefaultInstance() {
      return defaultInstance;
    }

    public UserInfoProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfoProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              headerImg_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              sex_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              position_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              address_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              motto_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              nameRemark_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              pwd_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              birthday_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              email_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              phone_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.miapsoft.opq.proto.UserInfo.internal_static_com_miapsoft_opq_proto_UserInfoProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.miapsoft.opq.proto.UserInfo.internal_static_com_miapsoft_opq_proto_UserInfoProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.miapsoft.opq.proto.UserInfo.UserInfoProto.class, com.miapsoft.opq.proto.UserInfo.UserInfoProto.Builder.class);
    }

    public static com.google.protobuf.Parser<UserInfoProto> PARSER =
        new com.google.protobuf.AbstractParser<UserInfoProto>() {
      public UserInfoProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserInfoProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfoProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString name_;
    /**
     * <code>optional bytes name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes name = 2;</code>
     */
    public com.google.protobuf.ByteString getName() {
      return name_;
    }

    // optional bytes headerImg = 3;
    public static final int HEADERIMG_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString headerImg_;
    /**
     * <code>optional bytes headerImg = 3;</code>
     */
    public boolean hasHeaderImg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes headerImg = 3;</code>
     */
    public com.google.protobuf.ByteString getHeaderImg() {
      return headerImg_;
    }

    // optional int32 sex = 4;
    public static final int SEX_FIELD_NUMBER = 4;
    private int sex_;
    /**
     * <code>optional int32 sex = 4;</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 sex = 4;</code>
     */
    public int getSex() {
      return sex_;
    }

    // optional bytes position = 5;
    public static final int POSITION_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString position_;
    /**
     * <code>optional bytes position = 5;</code>
     *
     * <pre>
     *地区
     * </pre>
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes position = 5;</code>
     *
     * <pre>
     *地区
     * </pre>
     */
    public com.google.protobuf.ByteString getPosition() {
      return position_;
    }

    // optional bytes address = 6;
    public static final int ADDRESS_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString address_;
    /**
     * <code>optional bytes address = 6;</code>
     *
     * <pre>
     *地址
     * </pre>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes address = 6;</code>
     *
     * <pre>
     *地址
     * </pre>
     */
    public com.google.protobuf.ByteString getAddress() {
      return address_;
    }

    // optional bytes motto = 7;
    public static final int MOTTO_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString motto_;
    /**
     * <code>optional bytes motto = 7;</code>
     *
     * <pre>
     *个性签名
     * </pre>
     */
    public boolean hasMotto() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bytes motto = 7;</code>
     *
     * <pre>
     *个性签名
     * </pre>
     */
    public com.google.protobuf.ByteString getMotto() {
      return motto_;
    }

    // optional bytes nameRemark = 8;
    public static final int NAMEREMARK_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString nameRemark_;
    /**
     * <code>optional bytes nameRemark = 8;</code>
     *
     * <pre>
     *备注
     * </pre>
     */
    public boolean hasNameRemark() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bytes nameRemark = 8;</code>
     *
     * <pre>
     *备注
     * </pre>
     */
    public com.google.protobuf.ByteString getNameRemark() {
      return nameRemark_;
    }

    // optional string pwd = 9;
    public static final int PWD_FIELD_NUMBER = 9;
    private java.lang.Object pwd_;
    /**
     * <code>optional string pwd = 9;</code>
     */
    public boolean hasPwd() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string pwd = 9;</code>
     */
    public java.lang.String getPwd() {
      java.lang.Object ref = pwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pwd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pwd = 9;</code>
     */
    public com.google.protobuf.ByteString
        getPwdBytes() {
      java.lang.Object ref = pwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string birthday = 10;
    public static final int BIRTHDAY_FIELD_NUMBER = 10;
    private java.lang.Object birthday_;
    /**
     * <code>optional string birthday = 10;</code>
     */
    public boolean hasBirthday() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string birthday = 10;</code>
     */
    public java.lang.String getBirthday() {
      java.lang.Object ref = birthday_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          birthday_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string birthday = 10;</code>
     */
    public com.google.protobuf.ByteString
        getBirthdayBytes() {
      java.lang.Object ref = birthday_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthday_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string email = 11;
    public static final int EMAIL_FIELD_NUMBER = 11;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 11;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string email = 11;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 11;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string phone = 12;
    public static final int PHONE_FIELD_NUMBER = 12;
    private java.lang.Object phone_;
    /**
     * <code>optional string phone = 12;</code>
     */
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string phone = 12;</code>
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          phone_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string phone = 12;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
      name_ = com.google.protobuf.ByteString.EMPTY;
      headerImg_ = com.google.protobuf.ByteString.EMPTY;
      sex_ = 0;
      position_ = com.google.protobuf.ByteString.EMPTY;
      address_ = com.google.protobuf.ByteString.EMPTY;
      motto_ = com.google.protobuf.ByteString.EMPTY;
      nameRemark_ = com.google.protobuf.ByteString.EMPTY;
      pwd_ = "";
      birthday_ = "";
      email_ = "";
      phone_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, headerImg_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, sex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, position_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, address_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, motto_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, nameRemark_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getPwdBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getBirthdayBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getEmailBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getPhoneBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, headerImg_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, sex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, position_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, address_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, motto_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, nameRemark_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getPwdBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getBirthdayBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getEmailBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getPhoneBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.miapsoft.opq.proto.UserInfo.UserInfoProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.miapsoft.opq.proto.UserInfo.UserInfoProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.UserInfo.UserInfoProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.miapsoft.opq.proto.UserInfo.UserInfoProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.UserInfo.UserInfoProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.miapsoft.opq.proto.UserInfo.UserInfoProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.UserInfo.UserInfoProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.miapsoft.opq.proto.UserInfo.UserInfoProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.UserInfo.UserInfoProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.miapsoft.opq.proto.UserInfo.UserInfoProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.miapsoft.opq.proto.UserInfo.UserInfoProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.miapsoft.opq.proto.UserInfoProto}
     *
     * <pre>
     *用户信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.miapsoft.opq.proto.UserInfo.UserInfoProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.miapsoft.opq.proto.UserInfo.internal_static_com_miapsoft_opq_proto_UserInfoProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.miapsoft.opq.proto.UserInfo.internal_static_com_miapsoft_opq_proto_UserInfoProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.miapsoft.opq.proto.UserInfo.UserInfoProto.class, com.miapsoft.opq.proto.UserInfo.UserInfoProto.Builder.class);
      }

      // Construct using com.miapsoft.opq.proto.UserInfo.UserInfoProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        headerImg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        position_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        address_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        motto_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        nameRemark_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        pwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        birthday_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        phone_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.miapsoft.opq.proto.UserInfo.internal_static_com_miapsoft_opq_proto_UserInfoProto_descriptor;
      }

      public com.miapsoft.opq.proto.UserInfo.UserInfoProto getDefaultInstanceForType() {
        return com.miapsoft.opq.proto.UserInfo.UserInfoProto.getDefaultInstance();
      }

      public com.miapsoft.opq.proto.UserInfo.UserInfoProto build() {
        com.miapsoft.opq.proto.UserInfo.UserInfoProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.miapsoft.opq.proto.UserInfo.UserInfoProto buildPartial() {
        com.miapsoft.opq.proto.UserInfo.UserInfoProto result = new com.miapsoft.opq.proto.UserInfo.UserInfoProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.headerImg_ = headerImg_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.position_ = position_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.motto_ = motto_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.nameRemark_ = nameRemark_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.pwd_ = pwd_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.birthday_ = birthday_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.phone_ = phone_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.miapsoft.opq.proto.UserInfo.UserInfoProto) {
          return mergeFrom((com.miapsoft.opq.proto.UserInfo.UserInfoProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.miapsoft.opq.proto.UserInfo.UserInfoProto other) {
        if (other == com.miapsoft.opq.proto.UserInfo.UserInfoProto.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasHeaderImg()) {
          setHeaderImg(other.getHeaderImg());
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasPosition()) {
          setPosition(other.getPosition());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasMotto()) {
          setMotto(other.getMotto());
        }
        if (other.hasNameRemark()) {
          setNameRemark(other.getNameRemark());
        }
        if (other.hasPwd()) {
          bitField0_ |= 0x00000100;
          pwd_ = other.pwd_;
          onChanged();
        }
        if (other.hasBirthday()) {
          bitField0_ |= 0x00000200;
          birthday_ = other.birthday_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000400;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasPhone()) {
          bitField0_ |= 0x00000800;
          phone_ = other.phone_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.miapsoft.opq.proto.UserInfo.UserInfoProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.miapsoft.opq.proto.UserInfo.UserInfoProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // optional bytes name = 2;
      private com.google.protobuf.ByteString name_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes name = 2;</code>
       */
      public com.google.protobuf.ByteString getName() {
        return name_;
      }
      /**
       * <code>optional bytes name = 2;</code>
       */
      public Builder setName(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }

      // optional bytes headerImg = 3;
      private com.google.protobuf.ByteString headerImg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes headerImg = 3;</code>
       */
      public boolean hasHeaderImg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes headerImg = 3;</code>
       */
      public com.google.protobuf.ByteString getHeaderImg() {
        return headerImg_;
      }
      /**
       * <code>optional bytes headerImg = 3;</code>
       */
      public Builder setHeaderImg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        headerImg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes headerImg = 3;</code>
       */
      public Builder clearHeaderImg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        headerImg_ = getDefaultInstance().getHeaderImg();
        onChanged();
        return this;
      }

      // optional int32 sex = 4;
      private int sex_ ;
      /**
       * <code>optional int32 sex = 4;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 sex = 4;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>optional int32 sex = 4;</code>
       */
      public Builder setSex(int value) {
        bitField0_ |= 0x00000008;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sex = 4;</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sex_ = 0;
        onChanged();
        return this;
      }

      // optional bytes position = 5;
      private com.google.protobuf.ByteString position_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes position = 5;</code>
       *
       * <pre>
       *地区
       * </pre>
       */
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes position = 5;</code>
       *
       * <pre>
       *地区
       * </pre>
       */
      public com.google.protobuf.ByteString getPosition() {
        return position_;
      }
      /**
       * <code>optional bytes position = 5;</code>
       *
       * <pre>
       *地区
       * </pre>
       */
      public Builder setPosition(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        position_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes position = 5;</code>
       *
       * <pre>
       *地区
       * </pre>
       */
      public Builder clearPosition() {
        bitField0_ = (bitField0_ & ~0x00000010);
        position_ = getDefaultInstance().getPosition();
        onChanged();
        return this;
      }

      // optional bytes address = 6;
      private com.google.protobuf.ByteString address_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes address = 6;</code>
       *
       * <pre>
       *地址
       * </pre>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes address = 6;</code>
       *
       * <pre>
       *地址
       * </pre>
       */
      public com.google.protobuf.ByteString getAddress() {
        return address_;
      }
      /**
       * <code>optional bytes address = 6;</code>
       *
       * <pre>
       *地址
       * </pre>
       */
      public Builder setAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes address = 6;</code>
       *
       * <pre>
       *地址
       * </pre>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000020);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }

      // optional bytes motto = 7;
      private com.google.protobuf.ByteString motto_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes motto = 7;</code>
       *
       * <pre>
       *个性签名
       * </pre>
       */
      public boolean hasMotto() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes motto = 7;</code>
       *
       * <pre>
       *个性签名
       * </pre>
       */
      public com.google.protobuf.ByteString getMotto() {
        return motto_;
      }
      /**
       * <code>optional bytes motto = 7;</code>
       *
       * <pre>
       *个性签名
       * </pre>
       */
      public Builder setMotto(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        motto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes motto = 7;</code>
       *
       * <pre>
       *个性签名
       * </pre>
       */
      public Builder clearMotto() {
        bitField0_ = (bitField0_ & ~0x00000040);
        motto_ = getDefaultInstance().getMotto();
        onChanged();
        return this;
      }

      // optional bytes nameRemark = 8;
      private com.google.protobuf.ByteString nameRemark_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes nameRemark = 8;</code>
       *
       * <pre>
       *备注
       * </pre>
       */
      public boolean hasNameRemark() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bytes nameRemark = 8;</code>
       *
       * <pre>
       *备注
       * </pre>
       */
      public com.google.protobuf.ByteString getNameRemark() {
        return nameRemark_;
      }
      /**
       * <code>optional bytes nameRemark = 8;</code>
       *
       * <pre>
       *备注
       * </pre>
       */
      public Builder setNameRemark(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        nameRemark_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes nameRemark = 8;</code>
       *
       * <pre>
       *备注
       * </pre>
       */
      public Builder clearNameRemark() {
        bitField0_ = (bitField0_ & ~0x00000080);
        nameRemark_ = getDefaultInstance().getNameRemark();
        onChanged();
        return this;
      }

      // optional string pwd = 9;
      private java.lang.Object pwd_ = "";
      /**
       * <code>optional string pwd = 9;</code>
       */
      public boolean hasPwd() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string pwd = 9;</code>
       */
      public java.lang.String getPwd() {
        java.lang.Object ref = pwd_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pwd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pwd = 9;</code>
       */
      public com.google.protobuf.ByteString
          getPwdBytes() {
        java.lang.Object ref = pwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pwd = 9;</code>
       */
      public Builder setPwd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        pwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pwd = 9;</code>
       */
      public Builder clearPwd() {
        bitField0_ = (bitField0_ & ~0x00000100);
        pwd_ = getDefaultInstance().getPwd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pwd = 9;</code>
       */
      public Builder setPwdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        pwd_ = value;
        onChanged();
        return this;
      }

      // optional string birthday = 10;
      private java.lang.Object birthday_ = "";
      /**
       * <code>optional string birthday = 10;</code>
       */
      public boolean hasBirthday() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string birthday = 10;</code>
       */
      public java.lang.String getBirthday() {
        java.lang.Object ref = birthday_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          birthday_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string birthday = 10;</code>
       */
      public com.google.protobuf.ByteString
          getBirthdayBytes() {
        java.lang.Object ref = birthday_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          birthday_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string birthday = 10;</code>
       */
      public Builder setBirthday(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        birthday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string birthday = 10;</code>
       */
      public Builder clearBirthday() {
        bitField0_ = (bitField0_ & ~0x00000200);
        birthday_ = getDefaultInstance().getBirthday();
        onChanged();
        return this;
      }
      /**
       * <code>optional string birthday = 10;</code>
       */
      public Builder setBirthdayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        birthday_ = value;
        onChanged();
        return this;
      }

      // optional string email = 11;
      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 11;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string email = 11;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 11;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 11;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 11;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000400);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 11;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        email_ = value;
        onChanged();
        return this;
      }

      // optional string phone = 12;
      private java.lang.Object phone_ = "";
      /**
       * <code>optional string phone = 12;</code>
       */
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string phone = 12;</code>
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string phone = 12;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string phone = 12;</code>
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 12;</code>
       */
      public Builder clearPhone() {
        bitField0_ = (bitField0_ & ~0x00000800);
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 12;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        phone_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.miapsoft.opq.proto.UserInfoProto)
    }

    static {
      defaultInstance = new UserInfoProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.miapsoft.opq.proto.UserInfoProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_miapsoft_opq_proto_UserInfoProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_miapsoft_opq_proto_UserInfoProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016UserInfo.proto\022\026com.miapsoft.opq.proto" +
      "\"\314\001\n\rUserInfoProto\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002" +
      " \001(\014\022\021\n\theaderImg\030\003 \001(\014\022\013\n\003sex\030\004 \001(\005\022\020\n\010" +
      "position\030\005 \001(\014\022\017\n\007address\030\006 \001(\014\022\r\n\005motto" +
      "\030\007 \001(\014\022\022\n\nnameRemark\030\010 \001(\014\022\013\n\003pwd\030\t \001(\t\022" +
      "\020\n\010birthday\030\n \001(\t\022\r\n\005email\030\013 \001(\t\022\r\n\005phon" +
      "e\030\014 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_miapsoft_opq_proto_UserInfoProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_miapsoft_opq_proto_UserInfoProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_miapsoft_opq_proto_UserInfoProto_descriptor,
              new java.lang.String[] { "Id", "Name", "HeaderImg", "Sex", "Position", "Address", "Motto", "NameRemark", "Pwd", "Birthday", "Email", "Phone", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
