// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserAlbum.proto

package com.miapsoft.opq.proto;

public final class UserAlbum {
  private UserAlbum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserAlbumProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string userId = 1;
    /**
     * <code>optional string userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional string userId = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>optional string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    // optional string albumId = 2;
    /**
     * <code>optional string albumId = 2;</code>
     */
    boolean hasAlbumId();
    /**
     * <code>optional string albumId = 2;</code>
     */
    java.lang.String getAlbumId();
    /**
     * <code>optional string albumId = 2;</code>
     */
    com.google.protobuf.ByteString
        getAlbumIdBytes();

    // optional bytes albumDes = 3;
    /**
     * <code>optional bytes albumDes = 3;</code>
     */
    boolean hasAlbumDes();
    /**
     * <code>optional bytes albumDes = 3;</code>
     */
    com.google.protobuf.ByteString getAlbumDes();

    // optional bytes albumName = 4;
    /**
     * <code>optional bytes albumName = 4;</code>
     */
    boolean hasAlbumName();
    /**
     * <code>optional bytes albumName = 4;</code>
     */
    com.google.protobuf.ByteString getAlbumName();

    // optional string albumTime = 5;
    /**
     * <code>optional string albumTime = 5;</code>
     */
    boolean hasAlbumTime();
    /**
     * <code>optional string albumTime = 5;</code>
     */
    java.lang.String getAlbumTime();
    /**
     * <code>optional string albumTime = 5;</code>
     */
    com.google.protobuf.ByteString
        getAlbumTimeBytes();
  }
  /**
   * Protobuf type {@code com.miapsoft.opq.proto.UserAlbumProto}
   *
   * <pre>
   *文件传输
   * </pre>
   */
  public static final class UserAlbumProto extends
      com.google.protobuf.GeneratedMessage
      implements UserAlbumProtoOrBuilder {
    // Use UserAlbumProto.newBuilder() to construct.
    private UserAlbumProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserAlbumProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserAlbumProto defaultInstance;
    public static UserAlbumProto getDefaultInstance() {
      return defaultInstance;
    }

    public UserAlbumProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserAlbumProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              albumId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              albumDes_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              albumName_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              albumTime_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.miapsoft.opq.proto.UserAlbum.internal_static_com_miapsoft_opq_proto_UserAlbumProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.miapsoft.opq.proto.UserAlbum.internal_static_com_miapsoft_opq_proto_UserAlbumProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.miapsoft.opq.proto.UserAlbum.UserAlbumProto.class, com.miapsoft.opq.proto.UserAlbum.UserAlbumProto.Builder.class);
    }

    public static com.google.protobuf.Parser<UserAlbumProto> PARSER =
        new com.google.protobuf.AbstractParser<UserAlbumProto>() {
      public UserAlbumProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserAlbumProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserAlbumProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userId_;
    /**
     * <code>optional string userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string albumId = 2;
    public static final int ALBUMID_FIELD_NUMBER = 2;
    private java.lang.Object albumId_;
    /**
     * <code>optional string albumId = 2;</code>
     */
    public boolean hasAlbumId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string albumId = 2;</code>
     */
    public java.lang.String getAlbumId() {
      java.lang.Object ref = albumId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          albumId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string albumId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAlbumIdBytes() {
      java.lang.Object ref = albumId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        albumId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes albumDes = 3;
    public static final int ALBUMDES_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString albumDes_;
    /**
     * <code>optional bytes albumDes = 3;</code>
     */
    public boolean hasAlbumDes() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes albumDes = 3;</code>
     */
    public com.google.protobuf.ByteString getAlbumDes() {
      return albumDes_;
    }

    // optional bytes albumName = 4;
    public static final int ALBUMNAME_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString albumName_;
    /**
     * <code>optional bytes albumName = 4;</code>
     */
    public boolean hasAlbumName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes albumName = 4;</code>
     */
    public com.google.protobuf.ByteString getAlbumName() {
      return albumName_;
    }

    // optional string albumTime = 5;
    public static final int ALBUMTIME_FIELD_NUMBER = 5;
    private java.lang.Object albumTime_;
    /**
     * <code>optional string albumTime = 5;</code>
     */
    public boolean hasAlbumTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string albumTime = 5;</code>
     */
    public java.lang.String getAlbumTime() {
      java.lang.Object ref = albumTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          albumTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string albumTime = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAlbumTimeBytes() {
      java.lang.Object ref = albumTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        albumTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userId_ = "";
      albumId_ = "";
      albumDes_ = com.google.protobuf.ByteString.EMPTY;
      albumName_ = com.google.protobuf.ByteString.EMPTY;
      albumTime_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAlbumIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, albumDes_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, albumName_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getAlbumTimeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAlbumIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, albumDes_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, albumName_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getAlbumTimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.miapsoft.opq.proto.UserAlbum.UserAlbumProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.miapsoft.opq.proto.UserAlbum.UserAlbumProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.UserAlbum.UserAlbumProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.miapsoft.opq.proto.UserAlbum.UserAlbumProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.UserAlbum.UserAlbumProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.miapsoft.opq.proto.UserAlbum.UserAlbumProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.UserAlbum.UserAlbumProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.miapsoft.opq.proto.UserAlbum.UserAlbumProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.UserAlbum.UserAlbumProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.miapsoft.opq.proto.UserAlbum.UserAlbumProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.miapsoft.opq.proto.UserAlbum.UserAlbumProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.miapsoft.opq.proto.UserAlbumProto}
     *
     * <pre>
     *文件传输
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.miapsoft.opq.proto.UserAlbum.UserAlbumProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.miapsoft.opq.proto.UserAlbum.internal_static_com_miapsoft_opq_proto_UserAlbumProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.miapsoft.opq.proto.UserAlbum.internal_static_com_miapsoft_opq_proto_UserAlbumProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.miapsoft.opq.proto.UserAlbum.UserAlbumProto.class, com.miapsoft.opq.proto.UserAlbum.UserAlbumProto.Builder.class);
      }

      // Construct using com.miapsoft.opq.proto.UserAlbum.UserAlbumProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        albumId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        albumDes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        albumName_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        albumTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.miapsoft.opq.proto.UserAlbum.internal_static_com_miapsoft_opq_proto_UserAlbumProto_descriptor;
      }

      public com.miapsoft.opq.proto.UserAlbum.UserAlbumProto getDefaultInstanceForType() {
        return com.miapsoft.opq.proto.UserAlbum.UserAlbumProto.getDefaultInstance();
      }

      public com.miapsoft.opq.proto.UserAlbum.UserAlbumProto build() {
        com.miapsoft.opq.proto.UserAlbum.UserAlbumProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.miapsoft.opq.proto.UserAlbum.UserAlbumProto buildPartial() {
        com.miapsoft.opq.proto.UserAlbum.UserAlbumProto result = new com.miapsoft.opq.proto.UserAlbum.UserAlbumProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.albumId_ = albumId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.albumDes_ = albumDes_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.albumName_ = albumName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.albumTime_ = albumTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.miapsoft.opq.proto.UserAlbum.UserAlbumProto) {
          return mergeFrom((com.miapsoft.opq.proto.UserAlbum.UserAlbumProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.miapsoft.opq.proto.UserAlbum.UserAlbumProto other) {
        if (other == com.miapsoft.opq.proto.UserAlbum.UserAlbumProto.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          bitField0_ |= 0x00000001;
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasAlbumId()) {
          bitField0_ |= 0x00000002;
          albumId_ = other.albumId_;
          onChanged();
        }
        if (other.hasAlbumDes()) {
          setAlbumDes(other.getAlbumDes());
        }
        if (other.hasAlbumName()) {
          setAlbumName(other.getAlbumName());
        }
        if (other.hasAlbumTime()) {
          bitField0_ |= 0x00000010;
          albumTime_ = other.albumTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.miapsoft.opq.proto.UserAlbum.UserAlbumProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.miapsoft.opq.proto.UserAlbum.UserAlbumProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string userId = 1;
      private java.lang.Object userId_ = "";
      /**
       * <code>optional string userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }

      // optional string albumId = 2;
      private java.lang.Object albumId_ = "";
      /**
       * <code>optional string albumId = 2;</code>
       */
      public boolean hasAlbumId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string albumId = 2;</code>
       */
      public java.lang.String getAlbumId() {
        java.lang.Object ref = albumId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          albumId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string albumId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAlbumIdBytes() {
        java.lang.Object ref = albumId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          albumId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string albumId = 2;</code>
       */
      public Builder setAlbumId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        albumId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string albumId = 2;</code>
       */
      public Builder clearAlbumId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        albumId_ = getDefaultInstance().getAlbumId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string albumId = 2;</code>
       */
      public Builder setAlbumIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        albumId_ = value;
        onChanged();
        return this;
      }

      // optional bytes albumDes = 3;
      private com.google.protobuf.ByteString albumDes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes albumDes = 3;</code>
       */
      public boolean hasAlbumDes() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes albumDes = 3;</code>
       */
      public com.google.protobuf.ByteString getAlbumDes() {
        return albumDes_;
      }
      /**
       * <code>optional bytes albumDes = 3;</code>
       */
      public Builder setAlbumDes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        albumDes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes albumDes = 3;</code>
       */
      public Builder clearAlbumDes() {
        bitField0_ = (bitField0_ & ~0x00000004);
        albumDes_ = getDefaultInstance().getAlbumDes();
        onChanged();
        return this;
      }

      // optional bytes albumName = 4;
      private com.google.protobuf.ByteString albumName_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes albumName = 4;</code>
       */
      public boolean hasAlbumName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes albumName = 4;</code>
       */
      public com.google.protobuf.ByteString getAlbumName() {
        return albumName_;
      }
      /**
       * <code>optional bytes albumName = 4;</code>
       */
      public Builder setAlbumName(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        albumName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes albumName = 4;</code>
       */
      public Builder clearAlbumName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        albumName_ = getDefaultInstance().getAlbumName();
        onChanged();
        return this;
      }

      // optional string albumTime = 5;
      private java.lang.Object albumTime_ = "";
      /**
       * <code>optional string albumTime = 5;</code>
       */
      public boolean hasAlbumTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string albumTime = 5;</code>
       */
      public java.lang.String getAlbumTime() {
        java.lang.Object ref = albumTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          albumTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string albumTime = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAlbumTimeBytes() {
        java.lang.Object ref = albumTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          albumTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string albumTime = 5;</code>
       */
      public Builder setAlbumTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        albumTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string albumTime = 5;</code>
       */
      public Builder clearAlbumTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        albumTime_ = getDefaultInstance().getAlbumTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string albumTime = 5;</code>
       */
      public Builder setAlbumTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        albumTime_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.miapsoft.opq.proto.UserAlbumProto)
    }

    static {
      defaultInstance = new UserAlbumProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.miapsoft.opq.proto.UserAlbumProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_miapsoft_opq_proto_UserAlbumProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_miapsoft_opq_proto_UserAlbumProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017UserAlbum.proto\022\026com.miapsoft.opq.prot" +
      "o\"i\n\016UserAlbumProto\022\016\n\006userId\030\001 \001(\t\022\017\n\007a" +
      "lbumId\030\002 \001(\t\022\020\n\010albumDes\030\003 \001(\014\022\021\n\talbumN" +
      "ame\030\004 \001(\014\022\021\n\talbumTime\030\005 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_miapsoft_opq_proto_UserAlbumProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_miapsoft_opq_proto_UserAlbumProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_miapsoft_opq_proto_UserAlbumProto_descriptor,
              new java.lang.String[] { "UserId", "AlbumId", "AlbumDes", "AlbumName", "AlbumTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
