// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserMsgResult.proto

package com.miapsoft.opq.proto;

public final class UserMsgResult {
  private UserMsgResult() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserMsgResultProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string fromId = 1;
    /**
     * <code>optional string fromId = 1;</code>
     */
    boolean hasFromId();
    /**
     * <code>optional string fromId = 1;</code>
     */
    java.lang.String getFromId();
    /**
     * <code>optional string fromId = 1;</code>
     */
    com.google.protobuf.ByteString
        getFromIdBytes();

    // optional string toId = 2;
    /**
     * <code>optional string toId = 2;</code>
     */
    boolean hasToId();
    /**
     * <code>optional string toId = 2;</code>
     */
    java.lang.String getToId();
    /**
     * <code>optional string toId = 2;</code>
     */
    com.google.protobuf.ByteString
        getToIdBytes();

    // optional string msgId = 3;
    /**
     * <code>optional string msgId = 3;</code>
     */
    boolean hasMsgId();
    /**
     * <code>optional string msgId = 3;</code>
     */
    java.lang.String getMsgId();
    /**
     * <code>optional string msgId = 3;</code>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    // optional int32 isSuccess = 4;
    /**
     * <code>optional int32 isSuccess = 4;</code>
     */
    boolean hasIsSuccess();
    /**
     * <code>optional int32 isSuccess = 4;</code>
     */
    int getIsSuccess();
  }
  /**
   * Protobuf type {@code com.miapsoft.opq.proto.UserMsgResultProto}
   *
   * <pre>
   *用户消息
   * </pre>
   */
  public static final class UserMsgResultProto extends
      com.google.protobuf.GeneratedMessage
      implements UserMsgResultProtoOrBuilder {
    // Use UserMsgResultProto.newBuilder() to construct.
    private UserMsgResultProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserMsgResultProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserMsgResultProto defaultInstance;
    public static UserMsgResultProto getDefaultInstance() {
      return defaultInstance;
    }

    public UserMsgResultProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserMsgResultProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fromId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              toId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              msgId_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              isSuccess_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.miapsoft.opq.proto.UserMsgResult.internal_static_com_miapsoft_opq_proto_UserMsgResultProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.miapsoft.opq.proto.UserMsgResult.internal_static_com_miapsoft_opq_proto_UserMsgResultProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto.class, com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto.Builder.class);
    }

    public static com.google.protobuf.Parser<UserMsgResultProto> PARSER =
        new com.google.protobuf.AbstractParser<UserMsgResultProto>() {
      public UserMsgResultProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserMsgResultProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserMsgResultProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string fromId = 1;
    public static final int FROMID_FIELD_NUMBER = 1;
    private java.lang.Object fromId_;
    /**
     * <code>optional string fromId = 1;</code>
     */
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string fromId = 1;</code>
     */
    public java.lang.String getFromId() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fromId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string toId = 2;
    public static final int TOID_FIELD_NUMBER = 2;
    private java.lang.Object toId_;
    /**
     * <code>optional string toId = 2;</code>
     */
    public boolean hasToId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string toId = 2;</code>
     */
    public java.lang.String getToId() {
      java.lang.Object ref = toId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string toId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getToIdBytes() {
      java.lang.Object ref = toId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string msgId = 3;
    public static final int MSGID_FIELD_NUMBER = 3;
    private java.lang.Object msgId_;
    /**
     * <code>optional string msgId = 3;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string msgId = 3;</code>
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 isSuccess = 4;
    public static final int ISSUCCESS_FIELD_NUMBER = 4;
    private int isSuccess_;
    /**
     * <code>optional int32 isSuccess = 4;</code>
     */
    public boolean hasIsSuccess() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 isSuccess = 4;</code>
     */
    public int getIsSuccess() {
      return isSuccess_;
    }

    private void initFields() {
      fromId_ = "";
      toId_ = "";
      msgId_ = "";
      isSuccess_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFromIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getToIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, isSuccess_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFromIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getToIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, isSuccess_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.miapsoft.opq.proto.UserMsgResultProto}
     *
     * <pre>
     *用户消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.miapsoft.opq.proto.UserMsgResult.internal_static_com_miapsoft_opq_proto_UserMsgResultProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.miapsoft.opq.proto.UserMsgResult.internal_static_com_miapsoft_opq_proto_UserMsgResultProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto.class, com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto.Builder.class);
      }

      // Construct using com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fromId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        toId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        isSuccess_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.miapsoft.opq.proto.UserMsgResult.internal_static_com_miapsoft_opq_proto_UserMsgResultProto_descriptor;
      }

      public com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto getDefaultInstanceForType() {
        return com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto.getDefaultInstance();
      }

      public com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto build() {
        com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto buildPartial() {
        com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto result = new com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fromId_ = fromId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.toId_ = toId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isSuccess_ = isSuccess_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto) {
          return mergeFrom((com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto other) {
        if (other == com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto.getDefaultInstance()) return this;
        if (other.hasFromId()) {
          bitField0_ |= 0x00000001;
          fromId_ = other.fromId_;
          onChanged();
        }
        if (other.hasToId()) {
          bitField0_ |= 0x00000002;
          toId_ = other.toId_;
          onChanged();
        }
        if (other.hasMsgId()) {
          bitField0_ |= 0x00000004;
          msgId_ = other.msgId_;
          onChanged();
        }
        if (other.hasIsSuccess()) {
          setIsSuccess(other.getIsSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.miapsoft.opq.proto.UserMsgResult.UserMsgResultProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string fromId = 1;
      private java.lang.Object fromId_ = "";
      /**
       * <code>optional string fromId = 1;</code>
       */
      public boolean hasFromId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string fromId = 1;</code>
       */
      public java.lang.String getFromId() {
        java.lang.Object ref = fromId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fromId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fromId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFromIdBytes() {
        java.lang.Object ref = fromId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fromId = 1;</code>
       */
      public Builder setFromId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fromId = 1;</code>
       */
      public Builder clearFromId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromId_ = getDefaultInstance().getFromId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fromId = 1;</code>
       */
      public Builder setFromIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fromId_ = value;
        onChanged();
        return this;
      }

      // optional string toId = 2;
      private java.lang.Object toId_ = "";
      /**
       * <code>optional string toId = 2;</code>
       */
      public boolean hasToId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string toId = 2;</code>
       */
      public java.lang.String getToId() {
        java.lang.Object ref = toId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          toId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string toId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getToIdBytes() {
        java.lang.Object ref = toId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string toId = 2;</code>
       */
      public Builder setToId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string toId = 2;</code>
       */
      public Builder clearToId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        toId_ = getDefaultInstance().getToId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string toId = 2;</code>
       */
      public Builder setToIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        toId_ = value;
        onChanged();
        return this;
      }

      // optional string msgId = 3;
      private java.lang.Object msgId_ = "";
      /**
       * <code>optional string msgId = 3;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string msgId = 3;</code>
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgId = 3;</code>
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgId = 3;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgId = 3;</code>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msgId_ = value;
        onChanged();
        return this;
      }

      // optional int32 isSuccess = 4;
      private int isSuccess_ ;
      /**
       * <code>optional int32 isSuccess = 4;</code>
       */
      public boolean hasIsSuccess() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 isSuccess = 4;</code>
       */
      public int getIsSuccess() {
        return isSuccess_;
      }
      /**
       * <code>optional int32 isSuccess = 4;</code>
       */
      public Builder setIsSuccess(int value) {
        bitField0_ |= 0x00000008;
        isSuccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 isSuccess = 4;</code>
       */
      public Builder clearIsSuccess() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isSuccess_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.miapsoft.opq.proto.UserMsgResultProto)
    }

    static {
      defaultInstance = new UserMsgResultProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.miapsoft.opq.proto.UserMsgResultProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_miapsoft_opq_proto_UserMsgResultProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_miapsoft_opq_proto_UserMsgResultProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023UserMsgResult.proto\022\026com.miapsoft.opq." +
      "proto\"T\n\022UserMsgResultProto\022\016\n\006fromId\030\001 " +
      "\001(\t\022\014\n\004toId\030\002 \001(\t\022\r\n\005msgId\030\003 \001(\t\022\021\n\tisSu" +
      "ccess\030\004 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_miapsoft_opq_proto_UserMsgResultProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_miapsoft_opq_proto_UserMsgResultProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_miapsoft_opq_proto_UserMsgResultProto_descriptor,
              new java.lang.String[] { "FromId", "ToId", "MsgId", "IsSuccess", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
