// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserFile.proto

package com.miapsoft.opq.proto;

public final class UserFile {
  private UserFile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserFileProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string fileId = 1;
    /**
     * <code>optional string fileId = 1;</code>
     */
    boolean hasFileId();
    /**
     * <code>optional string fileId = 1;</code>
     */
    java.lang.String getFileId();
    /**
     * <code>optional string fileId = 1;</code>
     */
    com.google.protobuf.ByteString
        getFileIdBytes();

    // optional bytes serverPath = 2;
    /**
     * <code>optional bytes serverPath = 2;</code>
     */
    boolean hasServerPath();
    /**
     * <code>optional bytes serverPath = 2;</code>
     */
    com.google.protobuf.ByteString getServerPath();

    // optional string fromId = 3;
    /**
     * <code>optional string fromId = 3;</code>
     */
    boolean hasFromId();
    /**
     * <code>optional string fromId = 3;</code>
     */
    java.lang.String getFromId();
    /**
     * <code>optional string fromId = 3;</code>
     */
    com.google.protobuf.ByteString
        getFromIdBytes();

    // optional string toId = 4;
    /**
     * <code>optional string toId = 4;</code>
     */
    boolean hasToId();
    /**
     * <code>optional string toId = 4;</code>
     */
    java.lang.String getToId();
    /**
     * <code>optional string toId = 4;</code>
     */
    com.google.protobuf.ByteString
        getToIdBytes();

    // optional uint64 length = 5;
    /**
     * <code>optional uint64 length = 5;</code>
     */
    boolean hasLength();
    /**
     * <code>optional uint64 length = 5;</code>
     */
    long getLength();

    // optional string fileTime = 6;
    /**
     * <code>optional string fileTime = 6;</code>
     */
    boolean hasFileTime();
    /**
     * <code>optional string fileTime = 6;</code>
     */
    java.lang.String getFileTime();
    /**
     * <code>optional string fileTime = 6;</code>
     */
    com.google.protobuf.ByteString
        getFileTimeBytes();
  }
  /**
   * Protobuf type {@code com.miapsoft.opq.proto.UserFileProto}
   *
   * <pre>
   *文件传输
   * </pre>
   */
  public static final class UserFileProto extends
      com.google.protobuf.GeneratedMessage
      implements UserFileProtoOrBuilder {
    // Use UserFileProto.newBuilder() to construct.
    private UserFileProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserFileProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserFileProto defaultInstance;
    public static UserFileProto getDefaultInstance() {
      return defaultInstance;
    }

    public UserFileProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserFileProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fileId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              serverPath_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              fromId_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              toId_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              length_ = input.readUInt64();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              fileTime_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.miapsoft.opq.proto.UserFile.internal_static_com_miapsoft_opq_proto_UserFileProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.miapsoft.opq.proto.UserFile.internal_static_com_miapsoft_opq_proto_UserFileProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.miapsoft.opq.proto.UserFile.UserFileProto.class, com.miapsoft.opq.proto.UserFile.UserFileProto.Builder.class);
    }

    public static com.google.protobuf.Parser<UserFileProto> PARSER =
        new com.google.protobuf.AbstractParser<UserFileProto>() {
      public UserFileProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserFileProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserFileProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string fileId = 1;
    public static final int FILEID_FIELD_NUMBER = 1;
    private java.lang.Object fileId_;
    /**
     * <code>optional string fileId = 1;</code>
     */
    public boolean hasFileId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string fileId = 1;</code>
     */
    public java.lang.String getFileId() {
      java.lang.Object ref = fileId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fileId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFileIdBytes() {
      java.lang.Object ref = fileId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes serverPath = 2;
    public static final int SERVERPATH_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString serverPath_;
    /**
     * <code>optional bytes serverPath = 2;</code>
     */
    public boolean hasServerPath() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes serverPath = 2;</code>
     */
    public com.google.protobuf.ByteString getServerPath() {
      return serverPath_;
    }

    // optional string fromId = 3;
    public static final int FROMID_FIELD_NUMBER = 3;
    private java.lang.Object fromId_;
    /**
     * <code>optional string fromId = 3;</code>
     */
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string fromId = 3;</code>
     */
    public java.lang.String getFromId() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fromId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string toId = 4;
    public static final int TOID_FIELD_NUMBER = 4;
    private java.lang.Object toId_;
    /**
     * <code>optional string toId = 4;</code>
     */
    public boolean hasToId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string toId = 4;</code>
     */
    public java.lang.String getToId() {
      java.lang.Object ref = toId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string toId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getToIdBytes() {
      java.lang.Object ref = toId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint64 length = 5;
    public static final int LENGTH_FIELD_NUMBER = 5;
    private long length_;
    /**
     * <code>optional uint64 length = 5;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint64 length = 5;</code>
     */
    public long getLength() {
      return length_;
    }

    // optional string fileTime = 6;
    public static final int FILETIME_FIELD_NUMBER = 6;
    private java.lang.Object fileTime_;
    /**
     * <code>optional string fileTime = 6;</code>
     */
    public boolean hasFileTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string fileTime = 6;</code>
     */
    public java.lang.String getFileTime() {
      java.lang.Object ref = fileTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fileTime = 6;</code>
     */
    public com.google.protobuf.ByteString
        getFileTimeBytes() {
      java.lang.Object ref = fileTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      fileId_ = "";
      serverPath_ = com.google.protobuf.ByteString.EMPTY;
      fromId_ = "";
      toId_ = "";
      length_ = 0L;
      fileTime_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFileIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, serverPath_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFromIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getToIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(5, length_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getFileTimeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFileIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, serverPath_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFromIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getToIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, length_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getFileTimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.miapsoft.opq.proto.UserFile.UserFileProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.miapsoft.opq.proto.UserFile.UserFileProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.UserFile.UserFileProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.miapsoft.opq.proto.UserFile.UserFileProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.UserFile.UserFileProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.miapsoft.opq.proto.UserFile.UserFileProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.UserFile.UserFileProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.miapsoft.opq.proto.UserFile.UserFileProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.miapsoft.opq.proto.UserFile.UserFileProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.miapsoft.opq.proto.UserFile.UserFileProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.miapsoft.opq.proto.UserFile.UserFileProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.miapsoft.opq.proto.UserFileProto}
     *
     * <pre>
     *文件传输
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.miapsoft.opq.proto.UserFile.UserFileProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.miapsoft.opq.proto.UserFile.internal_static_com_miapsoft_opq_proto_UserFileProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.miapsoft.opq.proto.UserFile.internal_static_com_miapsoft_opq_proto_UserFileProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.miapsoft.opq.proto.UserFile.UserFileProto.class, com.miapsoft.opq.proto.UserFile.UserFileProto.Builder.class);
      }

      // Construct using com.miapsoft.opq.proto.UserFile.UserFileProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fileId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        serverPath_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        fromId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        toId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        length_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        fileTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.miapsoft.opq.proto.UserFile.internal_static_com_miapsoft_opq_proto_UserFileProto_descriptor;
      }

      public com.miapsoft.opq.proto.UserFile.UserFileProto getDefaultInstanceForType() {
        return com.miapsoft.opq.proto.UserFile.UserFileProto.getDefaultInstance();
      }

      public com.miapsoft.opq.proto.UserFile.UserFileProto build() {
        com.miapsoft.opq.proto.UserFile.UserFileProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.miapsoft.opq.proto.UserFile.UserFileProto buildPartial() {
        com.miapsoft.opq.proto.UserFile.UserFileProto result = new com.miapsoft.opq.proto.UserFile.UserFileProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fileId_ = fileId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serverPath_ = serverPath_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fromId_ = fromId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.toId_ = toId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.fileTime_ = fileTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.miapsoft.opq.proto.UserFile.UserFileProto) {
          return mergeFrom((com.miapsoft.opq.proto.UserFile.UserFileProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.miapsoft.opq.proto.UserFile.UserFileProto other) {
        if (other == com.miapsoft.opq.proto.UserFile.UserFileProto.getDefaultInstance()) return this;
        if (other.hasFileId()) {
          bitField0_ |= 0x00000001;
          fileId_ = other.fileId_;
          onChanged();
        }
        if (other.hasServerPath()) {
          setServerPath(other.getServerPath());
        }
        if (other.hasFromId()) {
          bitField0_ |= 0x00000004;
          fromId_ = other.fromId_;
          onChanged();
        }
        if (other.hasToId()) {
          bitField0_ |= 0x00000008;
          toId_ = other.toId_;
          onChanged();
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasFileTime()) {
          bitField0_ |= 0x00000020;
          fileTime_ = other.fileTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.miapsoft.opq.proto.UserFile.UserFileProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.miapsoft.opq.proto.UserFile.UserFileProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string fileId = 1;
      private java.lang.Object fileId_ = "";
      /**
       * <code>optional string fileId = 1;</code>
       */
      public boolean hasFileId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string fileId = 1;</code>
       */
      public java.lang.String getFileId() {
        java.lang.Object ref = fileId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fileId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fileId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFileIdBytes() {
        java.lang.Object ref = fileId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fileId = 1;</code>
       */
      public Builder setFileId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileId = 1;</code>
       */
      public Builder clearFileId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fileId_ = getDefaultInstance().getFileId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileId = 1;</code>
       */
      public Builder setFileIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileId_ = value;
        onChanged();
        return this;
      }

      // optional bytes serverPath = 2;
      private com.google.protobuf.ByteString serverPath_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes serverPath = 2;</code>
       */
      public boolean hasServerPath() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes serverPath = 2;</code>
       */
      public com.google.protobuf.ByteString getServerPath() {
        return serverPath_;
      }
      /**
       * <code>optional bytes serverPath = 2;</code>
       */
      public Builder setServerPath(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        serverPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes serverPath = 2;</code>
       */
      public Builder clearServerPath() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverPath_ = getDefaultInstance().getServerPath();
        onChanged();
        return this;
      }

      // optional string fromId = 3;
      private java.lang.Object fromId_ = "";
      /**
       * <code>optional string fromId = 3;</code>
       */
      public boolean hasFromId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string fromId = 3;</code>
       */
      public java.lang.String getFromId() {
        java.lang.Object ref = fromId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fromId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fromId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFromIdBytes() {
        java.lang.Object ref = fromId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fromId = 3;</code>
       */
      public Builder setFromId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fromId = 3;</code>
       */
      public Builder clearFromId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fromId_ = getDefaultInstance().getFromId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fromId = 3;</code>
       */
      public Builder setFromIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fromId_ = value;
        onChanged();
        return this;
      }

      // optional string toId = 4;
      private java.lang.Object toId_ = "";
      /**
       * <code>optional string toId = 4;</code>
       */
      public boolean hasToId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string toId = 4;</code>
       */
      public java.lang.String getToId() {
        java.lang.Object ref = toId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          toId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string toId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getToIdBytes() {
        java.lang.Object ref = toId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string toId = 4;</code>
       */
      public Builder setToId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string toId = 4;</code>
       */
      public Builder clearToId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        toId_ = getDefaultInstance().getToId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string toId = 4;</code>
       */
      public Builder setToIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        toId_ = value;
        onChanged();
        return this;
      }

      // optional uint64 length = 5;
      private long length_ ;
      /**
       * <code>optional uint64 length = 5;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint64 length = 5;</code>
       */
      public long getLength() {
        return length_;
      }
      /**
       * <code>optional uint64 length = 5;</code>
       */
      public Builder setLength(long value) {
        bitField0_ |= 0x00000010;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 length = 5;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000010);
        length_ = 0L;
        onChanged();
        return this;
      }

      // optional string fileTime = 6;
      private java.lang.Object fileTime_ = "";
      /**
       * <code>optional string fileTime = 6;</code>
       */
      public boolean hasFileTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string fileTime = 6;</code>
       */
      public java.lang.String getFileTime() {
        java.lang.Object ref = fileTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fileTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fileTime = 6;</code>
       */
      public com.google.protobuf.ByteString
          getFileTimeBytes() {
        java.lang.Object ref = fileTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fileTime = 6;</code>
       */
      public Builder setFileTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        fileTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileTime = 6;</code>
       */
      public Builder clearFileTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        fileTime_ = getDefaultInstance().getFileTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileTime = 6;</code>
       */
      public Builder setFileTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        fileTime_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.miapsoft.opq.proto.UserFileProto)
    }

    static {
      defaultInstance = new UserFileProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.miapsoft.opq.proto.UserFileProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_miapsoft_opq_proto_UserFileProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_miapsoft_opq_proto_UserFileProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016UserFile.proto\022\026com.miapsoft.opq.proto" +
      "\"s\n\rUserFileProto\022\016\n\006fileId\030\001 \001(\t\022\022\n\nser" +
      "verPath\030\002 \001(\014\022\016\n\006fromId\030\003 \001(\t\022\014\n\004toId\030\004 " +
      "\001(\t\022\016\n\006length\030\005 \001(\004\022\020\n\010fileTime\030\006 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_miapsoft_opq_proto_UserFileProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_miapsoft_opq_proto_UserFileProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_miapsoft_opq_proto_UserFileProto_descriptor,
              new java.lang.String[] { "FileId", "ServerPath", "FromId", "ToId", "Length", "FileTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
